import {env} from "cloudflare:test";import {beforeAll,describe,expect,it} from "vitest";import {evaluateDue,ingestListings} from "../src/pipeline";import {MockCollector} from "../src/mock-collector";
import initial from "../migrations/0001_init.sql?raw";import research from "../migrations/0002_research_api.sql?raw";import safety from "../migrations/0003_research_safety.sql?raw";import buyback from "../migrations/0004_buyback_quotes.sql?raw";import buybackOpportunity from "../migrations/0005_buyback_opportunities.sql?raw";import live from "../migrations/0006_live_opportunities.sql?raw";import scores from "../migrations/0007_evaluation_scores.sql?raw";
function statements(migration:string){const out:string[]=[],lines=migration.split("\n");let buffer="",trigger=false;for(const line of lines){if(!trigger&&/^CREATE TRIGGER/i.test(line.trim()))trigger=true;buffer+=line+"\n";if(trigger){if(/^END;\s*$/i.test(line.trim())){out.push(buffer.trim().replace(/;$/,""));buffer="";trigger=false;}}else if(line.includes(";")){const parts=buffer.split(";");for(const part of parts.slice(0,-1))if(part.trim())out.push(part.trim());buffer=parts.at(-1)??"";}}if(buffer.trim())out.push(buffer.trim());return out;}
beforeAll(async()=>{for(const migration of [initial,research,safety,buyback,buybackOpportunity,live,scores])for(const sql of statements(migration))await env.DB.prepare(sql).run();});
const mockAt=async(at:string,buybackPrice?:number)=>{const items=await new MockCollector().collect(new Date(at));return items.map(item=>item.manufacturerPartNumber==="MTP03J/A"&&item.side==="purchase"?{...item,priceYen:100000}:buybackPrice!==undefined&&item.side==="buyback"&&item.manufacturerPartNumber==="MTP03J/A"?{...item,priceYen:item.source.endsWith("a")?buybackPrice:buybackPrice-500}:item);};
describe("real opportunity evaluator",()=>{
 it("keeps a due checkpoint pending when post-target data is unavailable",async()=>{const start="2026-04-01T00:00:00Z";await ingestListings(env.DB,await mockAt(start),new Date(start));const opportunity=await env.DB.prepare("SELECT id FROM research_opportunities ORDER BY id DESC LIMIT 1").first<any>();await evaluateDue(env.DB,new Date("2026-04-02T00:00:00Z"));expect(await env.DB.prepare("SELECT evaluation_status,market_profit_yen FROM research_opportunity_evaluations WHERE opportunity_id=? AND horizon_hours=24").bind(opportunity.id).first<any>()).toMatchObject({evaluation_status:"pending_data",market_profit_yen:null});});
 it.each([[105000,1],[104999,0]])("creates the 48h label at the 5,000 yen boundary",async(price,label)=>{const day=price===105000?1:10,start=`2026-05-${String(day).padStart(2,"0")}T00:00:00Z`,later=new Date(Date.parse(start)+48*3_600_000+5*60_000).toISOString();await ingestListings(env.DB,await mockAt(start,108000),new Date(start));const opportunity=await env.DB.prepare("SELECT id FROM research_opportunities WHERE detected_at=? AND market_profit_yen=8000 ORDER BY id DESC LIMIT 1").bind(new Date(start).toISOString()).first<any>();await ingestListings(env.DB,await mockAt(later,price),new Date(later));const row=await env.DB.prepare("SELECT * FROM research_opportunity_evaluations WHERE opportunity_id=? AND horizon_hours=48").bind(opportunity.id).first<any>();expect(row).toMatchObject({evaluation_status:"completed",market_profit_yen:price-100000,label_48h:label});});
 it("stores opportunity decay",async()=>{const start="2026-06-01T00:00:00Z",later="2026-06-02T00:05:00Z";await ingestListings(env.DB,await mockAt(start),new Date(start));const opportunity=await env.DB.prepare("SELECT id,market_profit_yen FROM research_opportunities WHERE detected_at=? AND market_profit_yen=8000 ORDER BY id DESC LIMIT 1").bind(new Date(start).toISOString()).first<any>();await ingestListings(env.DB,await mockAt(later,104000),new Date(later));const row=await env.DB.prepare("SELECT entry_market_profit_yen,market_profit_yen,decay_yen,decay_rate FROM research_opportunity_evaluations WHERE opportunity_id=? AND horizon_hours=24").bind(opportunity.id).first<any>();expect(row).toMatchObject({entry_market_profit_yen:8000,market_profit_yen:4000,decay_yen:-4000});expect(row.decay_rate).toBeCloseTo(-50,1);});
});
