import {env} from "cloudflare:test";
import {beforeAll,describe,expect,it} from "vitest";
import worker from "../src/index";
import {ingestListings,resolveProduct,runPipeline} from "../src/pipeline";
import {MockCollector} from "../src/mock-collector";
import initial from "../migrations/0001_init.sql?raw";
import research from "../migrations/0002_research_api.sql?raw";
import safety from "../migrations/0003_research_safety.sql?raw";
import buyback from "../migrations/0004_buyback_quotes.sql?raw";
import buybackOpportunity from "../migrations/0005_buyback_opportunities.sql?raw";
import liveOpportunities from "../migrations/0006_live_opportunities.sql?raw";
import evaluationScores from "../migrations/0007_evaluation_scores.sql?raw";

function statements(migration:string){const out:string[]=[],lines=migration.split("\n");let buffer="",trigger=false;for(const line of lines){if(!trigger&&/^CREATE TRIGGER/i.test(line.trim()))trigger=true;buffer+=line+"\n";if(trigger){if(/^END;\s*$/i.test(line.trim())){out.push(buffer.trim().replace(/;$/,""));buffer="";trigger=false;}}else if(line.includes(";")){const parts=buffer.split(";");for(const part of parts.slice(0,-1))if(part.trim())out.push(part.trim());buffer=parts.at(-1)??"";}}if(buffer.trim())out.push(buffer.trim());return out;}
beforeAll(async()=>{for(const migration of [initial,research,safety,buyback,buybackOpportunity,liveOpportunities,evaluationScores])for(const sql of statements(migration))await env.DB.prepare(sql).run();});

describe("Research Worker",()=>{
 it("keeps the mock vertical slice idempotent and within the 300k portfolio",async()=>{const at=new Date("2026-01-01T00:00:00Z"),first=await runPipeline(env.DB,new MockCollector(),at),again=await runPipeline(env.DB,new MockCollector(),at);expect(first.observations).toBe(5);expect(first.products).toBe(2);expect(first.snapshots).toBe(5);expect(first.opportunities).toBe(2);expect(first.buys).toBe(1);expect(again.snapshots).toBe(0);expect(again.buys).toBe(0);const account=await env.DB.prepare("SELECT * FROM research_paper_accounts").first<any>();expect(account.initial_cash_yen).toBe(300000);expect(account.available_cash_yen).toBeGreaterThanOrEqual(0);});
 it("rejects ambiguous model-only resolution",async()=>{await expect(resolveProduct(env.DB,{source:"x",externalId:"1",side:"purchase",title:"Generic",model:"X",priceYen:1,stock:1,capturedAt:new Date().toISOString()})).rejects.toThrow("precision-safe");});
 it("keeps multiple buybacks and derives score and second price",async()=>{await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));const o=await env.DB.prepare("SELECT * FROM research_opportunities WHERE buyback_store_count>=2 ORDER BY id DESC LIMIT 1").first<any>();expect(o.buyback_store_count).toBe(2);expect(o.second_buyback_price_yen).toBeGreaterThan(0);expect(o.sprea_score).toBeGreaterThan(0);});
 it("evaluates 24/48/72/168 hours once and realizes proceeds on close",async()=>{const start=Date.parse("2026-01-01T00:00:00Z");await runPipeline(env.DB,new MockCollector(),new Date(start));for(const hours of [24,48,72,168])await runPipeline(env.DB,new MockCollector(),new Date(start+hours*3_600_000));const rows=await env.DB.prepare("SELECT horizon_hours FROM research_evaluations ORDER BY horizon_hours").all<any>();expect([...new Set(rows.results.map(x=>x.horizon_hours))]).toEqual([24,48,72,168]);const duplicates=await env.DB.prepare(`SELECT o.canonical_product_id,COUNT(*) count FROM research_paper_trades t JOIN research_opportunities o ON o.id=t.opportunity_id WHERE t.status='OPEN' GROUP BY o.canonical_product_id HAVING COUNT(*)>1`).all();expect(duplicates.results).toHaveLength(0);const account=await env.DB.prepare("SELECT * FROM research_paper_accounts").first<any>();expect(account.reserved_cash_yen).toBe(0);expect(account.available_cash_yen).toBeGreaterThan(300000);});
 it("authenticates and validates real listing ingest",async()=>{const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const,ALLOWED_ORIGIN:"http://localhost:3000"} as Env;const listing={source:"official-feed",externalId:"sku-1",side:"purchase",title:"Camera X body",brand:"Maker",model:"X",variant:"body",manufacturerPartNumber:"CAM-X",priceYen:80000,stock:1,capturedAt:"2026-02-01T00:00:00.000Z"};const unauthorized=await worker.fetch!(new Request("http://test/api/ingest/listings",{method:"POST",body:JSON.stringify({runId:"r1",source:"official-feed",listings:[listing]})}),e);expect(unauthorized.status).toBe(401);const accepted=await worker.fetch!(new Request("http://test/api/ingest/listings",{method:"POST",headers:{authorization:"Bearer ingest-secret","content-type":"application/json"},body:JSON.stringify({runId:"r1",source:"official-feed",listings:[listing]})}),e);expect(accepted.status).toBe(202);expect((await accepted.json() as any).observations).toBe(1);});
 it("accepts the documented retailer/buyback wire contract",async()=>{const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;const listing={source:"partner-feed",sourceType:"retailer",externalId:"wire-1",productName:"Game Console Standard",jan:"4900000000001",modelNumber:"GC-STD",brand:"Maker",category:"game_console",condition:"new",attributes:{edition:"Standard",discDrive:true},price:50000,shippingFee:0,fee:0,reward:0,stock:1,productUrl:"https://example.invalid/item/1",fetchedAt:"2026-02-02T00:00:00.000Z"};const response=await worker.fetch!(new Request("http://test/api/ingest/listings",{method:"POST",headers:{authorization:"Bearer ingest-secret","content-type":"application/json"},body:JSON.stringify({runId:"wire-run",source:"partner-feed",listings:[listing]})}),e);expect(response.status).toBe(202);const product=await env.DB.prepare("SELECT brand,category,gtin FROM canonical_products WHERE gtin='4900000000001'").first<any>();expect(product).toMatchObject({brand:"Maker",category:"game_console",gtin:"4900000000001"});});
 it("exposes only fresh in-stock purchase JANs to authenticated collectors",async()=>{const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;await ingestListings(env.DB,[{source:"fresh-shop",externalId:"fresh",side:"purchase",title:"Fresh camera",gtin:"4900000000999",brand:"Maker",model:"Fresh",variant:"body",priceYen:80000,stock:1,capturedAt:new Date().toISOString()}],new Date());const denied=await worker.fetch!(new Request("http://test/api/ingest/targets"),e);expect(denied.status).toBe(401);const response=await worker.fetch!(new Request("http://test/api/ingest/targets",{headers:{authorization:"Bearer ingest-secret"}}),e);expect(response.status).toBe(200);const body=await response.json() as any;expect(body.targets.length).toBeGreaterThan(0);expect(body.targets.every((x:any)=>/^\d{8,14}$/.test(x.gtin)&&x.purchasePrice>0)).toBe(true);});
 it("exposes product, settings, trades, evaluator, and collector status APIs",async()=>{await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;for(const path of ["/api/research/dashboard","/api/research/paper-trades","/api/research/settings","/api/research/evaluator","/api/collector/status"]){const response=await worker.fetch!(new Request(`http://test${path}`,{headers:{authorization:"Bearer admin-secret"}}),e);expect(response.status,path).toBe(200);}const product=await env.DB.prepare("SELECT canonical_key FROM canonical_products LIMIT 1").first<any>();const response=await worker.fetch!(new Request(`http://test/api/research/products/${encodeURIComponent(product.canonical_key)}`,{headers:{authorization:"Bearer admin-secret"}}),e);expect(response.status).toBe(200);expect((await response.json() as any).history.length).toBeGreaterThan(0);});
 it("returns only the latest dashboard opportunity for each canonical product",async()=>{const e={...env,ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;const response=await worker.fetch!(new Request("http://test/api/research/dashboard",{headers:{authorization:"Bearer admin-secret"}}),e);const body=await response.json() as any;const keys=body.opportunities.map((x:any)=>x.canonicalKey);expect(new Set(keys).size).toBe(keys.length);});
});

describe("Research safety invariants",()=>{
 const fixed=(at:string)=>[
  {source:"fixed-shop",externalId:"p",side:"purchase" as const,title:"Camera X body",url:"https://example.test/camera-x",brand:"Maker",model:"Camera X",variant:"body",manufacturerPartNumber:"CAM-X",priceYen:100000,shippingYen:0,feeYen:0,rewardYen:0,stock:1,capturedAt:at},
  {source:"fixed-buyback",externalId:"b",side:"buyback" as const,title:"Camera X buyback",brand:"Maker",model:"Camera X",variant:"body",manufacturerPartNumber:"CAM-X",priceYen:106000,shippingYen:0,feeYen:0,rewardYen:0,stock:1,capturedAt:at}
 ];
 it("evaluates unchanged prices at 48h without writing duplicate snapshots",async()=>{const start="2026-03-01T00:00:00.000Z";await ingestListings(env.DB,fixed(start),new Date(start));const snapshotsBefore=(await env.DB.prepare("SELECT COUNT(*) count FROM research_price_snapshots").first<any>()).count;const later="2026-03-03T00:00:00.000Z",result=await ingestListings(env.DB,fixed(later),new Date(later));expect(result.snapshots).toBe(0);expect((await env.DB.prepare("SELECT COUNT(*) count FROM research_price_snapshots").first<any>()).count).toBe(snapshotsBefore);const evaluation=await env.DB.prepare("SELECT profit_yen,target_met FROM research_evaluations WHERE horizon_hours=48").first<any>();expect(evaluation.profit_yen).toBe(6000);expect(evaluation.target_met).toBe(1);});
 it("applies fixed sale costs identically to entry and evaluation",async()=>{await env.DB.prepare("UPDATE research_settings SET fees_yen=1000 WHERE id=1").run();const start="2026-03-01T00:00:00.000Z";await ingestListings(env.DB,fixed(start),new Date(start));const later="2026-03-03T00:00:00.000Z";await ingestListings(env.DB,fixed(later),new Date(later));const opp=await env.DB.prepare("SELECT market_profit_yen FROM research_opportunities").first<any>(),evaluation=await env.DB.prepare("SELECT profit_yen FROM research_evaluations WHERE horizon_hours=48").first<any>();expect(opp.market_profit_yen).toBe(5000);expect(evaluation.profit_yen).toBe(5000);});
 it("settles a trade exactly once even when close is retried",async()=>{await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));const trade=await env.DB.prepare("SELECT id FROM research_paper_trades WHERE status='OPEN'").first<any>(),before=await env.DB.prepare("SELECT available_cash_yen FROM research_paper_accounts").first<any>();await env.DB.prepare("UPDATE research_paper_trades SET status='CLOSED',settlement_revenue_yen=108000,closed_at=? WHERE id=? AND status='OPEN'").bind("2026-01-02T00:00:00Z",trade.id).run();await env.DB.prepare("UPDATE research_paper_trades SET status='CLOSED',settlement_revenue_yen=108000,closed_at=? WHERE id=? AND status='OPEN'").bind("2026-01-02T00:00:00Z",trade.id).run();const after=await env.DB.prepare("SELECT available_cash_yen,reserved_cash_yen FROM research_paper_accounts").first<any>(),ledger=await env.DB.prepare("SELECT COUNT(*) count FROM paper_settlement_ledger WHERE trade_id=?").bind(trade.id).first<any>();expect(ledger.count).toBe(1);expect(after.available_cash_yen-before.available_cash_yen).toBe(108000);expect(after.reserved_cash_yen).toBe(0);});
 it("rejects unfunded positions inside the database trigger",async()=>{await env.DB.prepare("UPDATE research_paper_accounts SET available_cash_yen=50000 WHERE id=1").run();await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));expect((await env.DB.prepare("SELECT COUNT(*) count FROM research_paper_trades").first<any>()).count).toBe(0);expect((await env.DB.prepare("SELECT available_cash_yen FROM research_paper_accounts").first<any>()).available_cash_yen).toBe(50000);});
 it("fails closed when strong canonical aliases disagree",async()=>{const base=fixed("2026-03-01T00:00:00.000Z")[0];await resolveProduct(env.DB,{...base,gtin:"12345678"});await expect(resolveProduct(env.DB,{...base,externalId:"other",gtin:"87654321"})).rejects.toThrow("conflicting GTIN");});
 it("requires admin Bearer auth for every private read and syncs initial capital",async()=>{const e={...env,ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;const denied=await worker.fetch!(new Request("http://test/api/research/dashboard"),e);expect(denied.status).toBe(401);const update=await worker.fetch!(new Request("http://test/api/research/settings",{method:"PUT",headers:{authorization:"Bearer admin-secret","content-type":"application/json"},body:JSON.stringify({initialCapital:350000,minimumProfit:5000,minimumConfidence:.95,saleShipping:0,fees:0,evaluationHours:[24,48,72,168],maxPriceAgeMinutes:60})}),e);expect(update.status).toBe(200);const account=await env.DB.prepare("SELECT initial_cash_yen,available_cash_yen FROM research_paper_accounts").first<any>();expect(account.initial_cash_yen).toBe(350000);expect(account.available_cash_yen).toBe(350000);});
 it("does not pair a fresh quote with a stale counterparty",async()=>{const start="2026-03-01T00:00:00.000Z";await ingestListings(env.DB,[fixed(start)[0]],new Date(start));const later="2026-03-01T02:00:00.000Z";await ingestListings(env.DB,[{...fixed(later)[1]}],new Date(later));expect((await env.DB.prepare("SELECT COUNT(*) count FROM research_opportunities").first<any>()).count).toBe(0);});
});
