import {env} from "cloudflare:test";
import {beforeAll,describe,expect,it,vi} from "vitest";
import worker from "../src/index";
import {ingestListings,paperTradeSkipReason,resolveProduct,runPipeline} from "../src/pipeline";
import {MockCollector} from "../src/mock-collector";
import initial from "../migrations/0001_init.sql?raw";
import research from "../migrations/0002_research_api.sql?raw";
import safety from "../migrations/0003_research_safety.sql?raw";
import buyback from "../migrations/0004_buyback_quotes.sql?raw";
import buybackOpportunity from "../migrations/0005_buyback_opportunities.sql?raw";
import liveOpportunities from "../migrations/0006_live_opportunities.sql?raw";
import evaluationScores from "../migrations/0007_evaluation_scores.sql?raw";
import decisionObservability from "../migrations/0008_decision_observability.sql?raw";
import productDiscovery from "../migrations/0009_product_discovery.sql?raw";
import providerDiscovery from "../migrations/0010_provider_discovery.sql?raw";
import buybackDailyStats from "../migrations/0012_buyback_daily_stats.sql?raw";
import discoveryReadOptimization from "../migrations/0013_discovery_read_optimization.sql?raw";
import materializedDiscoveryQueue from "../migrations/0014_materialized_discovery_queue.sql?raw";
import csvRetentionCleanup from "../migrations/0015_csv_retention_cleanup.sql?raw";
import {buildDiscoveryCandidates,markDiscoveryQueueDirty,runProductDiscovery} from "../src/discovery";

function statements(migration:string){const out:string[]=[],lines=migration.split("\n");let buffer="",trigger=false;for(const line of lines){if(!trigger&&/^CREATE TRIGGER/i.test(line.trim()))trigger=true;buffer+=line+"\n";if(trigger){if(/^END;\s*$/i.test(line.trim())){out.push(buffer.trim().replace(/;$/,""));buffer="";trigger=false;}}else if(line.includes(";")){const parts=buffer.split(";");for(const part of parts.slice(0,-1))if(part.trim())out.push(part.trim());buffer=parts.at(-1)??"";}}if(buffer.trim())out.push(buffer.trim());return out;}
beforeAll(async()=>{for(const migration of [initial,research,safety,buyback,buybackOpportunity,liveOpportunities,evaluationScores,decisionObservability,productDiscovery,providerDiscovery,buybackDailyStats,discoveryReadOptimization,materializedDiscoveryQueue,csvRetentionCleanup])for(const sql of statements(migration))await env.DB.prepare(sql).run();});

describe("Research Worker",()=>{
 it("classifies paper-trading constraints as structured SKIP reasons",()=>{expect(paperTradeSkipReason("open position already exists")).toBe("duplicate_holding");expect(paperTradeSkipReason("insufficient paper cash")).toBe("insufficient_funds");expect(paperTradeSkipReason("other database error")).toBeNull();});
 it("keeps the mock vertical slice idempotent and within the 300k portfolio",async()=>{const at=new Date("2026-01-01T00:00:00Z"),first=await runPipeline(env.DB,new MockCollector(),at),again=await runPipeline(env.DB,new MockCollector(),at);expect(first.observations).toBe(5);expect(first.products).toBe(2);expect(first.snapshots).toBe(5);expect(first.opportunities).toBe(2);expect(first.buys).toBe(1);expect(again.snapshots).toBe(0);expect(again.buys).toBe(0);const account=await env.DB.prepare("SELECT * FROM research_paper_accounts").first<any>();expect(account.initial_cash_yen).toBe(300000);expect(account.available_cash_yen).toBeGreaterThanOrEqual(0);});
 it("rejects ambiguous model-only resolution",async()=>{await expect(resolveProduct(env.DB,{source:"x",externalId:"1",side:"purchase",title:"Generic",model:"X",priceYen:1,stock:1,capturedAt:new Date().toISOString()})).rejects.toThrow("precision-safe");});
 it("keeps multiple buybacks and derives score and second price",async()=>{await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));const o=await env.DB.prepare("SELECT * FROM research_opportunities WHERE buyback_store_count>=2 ORDER BY id DESC LIMIT 1").first<any>();expect(o.buyback_store_count).toBe(2);expect(o.second_buyback_price_yen).toBeGreaterThan(0);expect(o.sprea_score).toBeGreaterThan(0);});
 it("evaluates 24/48/72/168 hours once and realizes proceeds on close",async()=>{const start=Date.parse("2026-01-01T00:00:00Z");await runPipeline(env.DB,new MockCollector(),new Date(start));for(const hours of [24,48,72,168])await runPipeline(env.DB,new MockCollector(),new Date(start+hours*3_600_000));const rows=await env.DB.prepare("SELECT horizon_hours FROM research_evaluations ORDER BY horizon_hours").all<any>();expect([...new Set(rows.results.map(x=>x.horizon_hours))]).toEqual([24,48,72,168]);const duplicates=await env.DB.prepare(`SELECT o.canonical_product_id,COUNT(*) count FROM research_paper_trades t JOIN research_opportunities o ON o.id=t.opportunity_id WHERE t.status='OPEN' GROUP BY o.canonical_product_id HAVING COUNT(*)>1`).all();expect(duplicates.results).toHaveLength(0);const account=await env.DB.prepare("SELECT * FROM research_paper_accounts").first<any>();expect(account.reserved_cash_yen).toBe(0);expect(account.available_cash_yen).toBeGreaterThan(300000);});
 it("authenticates and validates real listing ingest",async()=>{const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const,ALLOWED_ORIGIN:"http://localhost:3000"} as Env;const listing={source:"official-feed",externalId:"sku-1",side:"purchase",title:"Camera X body",brand:"Maker",model:"X",variant:"body",manufacturerPartNumber:"CAM-X",priceYen:80000,stock:1,capturedAt:"2026-02-01T00:00:00.000Z"};const unauthorized=await worker.fetch!(new Request("http://test/api/ingest/listings",{method:"POST",body:JSON.stringify({runId:"r1",source:"official-feed",listings:[listing]})}),e);expect(unauthorized.status).toBe(401);const accepted=await worker.fetch!(new Request("http://test/api/ingest/listings",{method:"POST",headers:{authorization:"Bearer ingest-secret","content-type":"application/json"},body:JSON.stringify({runId:"r1",source:"official-feed",listings:[listing]})}),e);expect(accepted.status).toBe(202);expect((await accepted.json() as any).observations).toBe(1);});
 it("accepts the documented retailer/buyback wire contract",async()=>{const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;const listing={source:"partner-feed",sourceType:"retailer",externalId:"wire-1",productName:"Game Console Standard",jan:"4900000000001",modelNumber:"GC-STD",brand:"Maker",category:"game_console",condition:"new",attributes:{edition:"Standard",discDrive:true},price:50000,shippingFee:0,fee:0,reward:0,stock:1,productUrl:"https://example.invalid/item/1",fetchedAt:"2026-02-02T00:00:00.000Z"};const response=await worker.fetch!(new Request("http://test/api/ingest/listings",{method:"POST",headers:{authorization:"Bearer ingest-secret","content-type":"application/json"},body:JSON.stringify({runId:"wire-run",source:"partner-feed",listings:[listing]})}),e);expect(response.status).toBe(202);const product=await env.DB.prepare("SELECT brand,category,gtin FROM canonical_products WHERE gtin='4900000000001'").first<any>();expect(product).toMatchObject({brand:"Maker",category:"game_console",gtin:"4900000000001"});});
 it("exposes only fresh in-stock purchase JANs to authenticated collectors",async()=>{const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;await ingestListings(env.DB,[{source:"fresh-shop",externalId:"fresh",side:"purchase",title:"Fresh camera",gtin:"4900000000999",brand:"Maker",model:"Fresh",variant:"body",priceYen:80000,stock:1,capturedAt:new Date().toISOString()}],new Date());const denied=await worker.fetch!(new Request("http://test/api/ingest/targets"),e);expect(denied.status).toBe(401);const response=await worker.fetch!(new Request("http://test/api/ingest/targets",{headers:{authorization:"Bearer ingest-secret"}}),e);expect(response.status).toBe(200);const body=await response.json() as any;expect(body.targets.length).toBeGreaterThan(0);expect(body.targets.every((x:any)=>/^\d{8,14}$/.test(x.gtin)&&x.purchasePrice>0)).toBe(true);});
 it("exposes product, settings, trades, evaluator, and collector status APIs",async()=>{await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));const e={...env,INGEST_API_KEY:"ingest-secret",ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const};for(const path of ["/api/research/dashboard","/api/research/paper-trades","/api/research/settings","/api/research/evaluator","/api/research/analytics","/api/collector/status","/api/kaitorix/csv/status"]){const response=await worker.fetch!(new Request(`http://test${path}`,{headers:{authorization:"Bearer admin-secret"}}),e);expect(response.status,path).toBe(200);}const product=await env.DB.prepare("SELECT canonical_key FROM canonical_products LIMIT 1").first<any>();const response=await worker.fetch!(new Request(`http://test/api/research/products/${encodeURIComponent(product.canonical_key)}`,{headers:{authorization:"Bearer admin-secret"}}),e);expect(response.status).toBe(200);expect((await response.json() as any).history.length).toBeGreaterThan(0);});
 it("returns discovery candidates as a bounded page",async()=>{await buildDiscoveryCandidates(env.DB,new Date("2026-04-01T00:00:00Z"));const response=await worker.fetch!(new Request("http://test/api/research/discovery-candidates?limit=1&page=1"),env);expect(response.status).toBe(200);const body=await response.json() as any;expect(body.page).toBe(1);expect(body.pageSize).toBe(1);expect(body.items.length).toBeLessThanOrEqual(1);expect(typeof body.hasNext).toBe("boolean");});
 it("reads only due provider-state rows after a queue rebuild",async()=>{const at=new Date("2030-01-01T00:00:00.000Z"),candidate=await env.DB.prepare(`INSERT INTO product_discovery_candidates(identity_key,canonical_product_id,jan,model_number,product_name,brand,category,condition,attributes_json,best_buyback_price_yen,best_buyback_provider,buyback_provider_count,resolver_status,resolver_confidence,resolver_reason,search_query,target_purchase_price_yen,discovery_ceiling_yen,next_search_at,first_seen_at,last_seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind("queue-test:new",null,null,"M1","Queue test","Maker","other","new","{}",10000,"store-a",1,"searchable",.99,"model_exact","M1",5000,8000,at.toISOString(),at.toISOString(),at.toISOString(),at.toISOString()).run(),candidateId=Number(candidate.meta.last_row_id);await env.DB.prepare("UPDATE product_discovery_queue_meta SET dirty=0,reset_requested=0,provider_signature='yahoo',candidate_count=1,quote_count=0,canonical_count=0 WHERE id=1").run();await env.DB.prepare("INSERT INTO product_discovery_provider_state(candidate_id,provider,status,attempt_count,failure_count,last_searched_at,next_search_at,last_error,updated_at,queue_priority_yen) VALUES(?,?, 'pending',0,0,NULL,?,'',?,?)").bind(candidateId,"yahoo",at.toISOString(),at.toISOString(),10000).run();vi.stubGlobal("fetch",async()=>new Response(JSON.stringify({hits:[]}),{status:200}));try{const first=await runProductDiscovery({DB:env.DB,YAHOO_CLIENT_ID:"test"},"manual",1,at);expect(first.searched).toBe(1);const state=await env.DB.prepare("SELECT attempt_count,next_search_at FROM product_discovery_provider_state WHERE candidate_id=? AND provider='yahoo'").bind(candidateId).first<any>();expect(state.attempt_count).toBe(1);expect(state.next_search_at).toBe("2030-01-01T06:00:00.000Z");const second=await runProductDiscovery({DB:env.DB,YAHOO_CLIENT_ID:"test"},"manual",1,new Date("2030-01-01T00:05:00.000Z"));expect(second.searched).toBe(0);}finally{vi.unstubAllGlobals();}});
 it("keeps a large scheduled queue lookup bounded per provider",async()=>{
  const at=new Date("2040-01-01T00:00:00.000Z"),prefix="queue-load-",candidateSql=`INSERT INTO product_discovery_candidates(identity_key,canonical_product_id,jan,model_number,product_name,brand,category,condition,attributes_json,best_buyback_price_yen,best_buyback_provider,buyback_provider_count,resolver_status,resolver_confidence,resolver_reason,search_query,target_purchase_price_yen,discovery_ceiling_yen,next_search_at,first_seen_at,last_seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`;
  // Isolate this integration fixture so it represents the same 10k-candidate
  // production queue without affecting the other database tests.
  await env.DB.prepare("DELETE FROM product_discovery_results").run();
  await env.DB.prepare("DELETE FROM product_discovery_provider_runs").run();
  await env.DB.prepare("DELETE FROM product_discovery_runs").run();
  await env.DB.prepare("DELETE FROM product_discovery_provider_state").run();
  await env.DB.prepare("DELETE FROM product_discovery_candidates").run();
  const candidates=Array.from({length:10_000},(_,index)=>env.DB.prepare(candidateSql).bind(`${prefix}${index}`,null,`4900000${String(index).padStart(6,"0")}`,`LOAD-${index}`,`Queue load ${index}`,"Maker","other","new","{}",10000,"store-a",1,"searchable",.99,"model_exact",`LOAD-${index}`,5000,8000,at.toISOString(),at.toISOString(),at.toISOString(),at.toISOString()));
  for(let index=0;index<candidates.length;index+=100)await env.DB.batch(candidates.slice(index,index+100));
  const ids=(await env.DB.prepare("SELECT id FROM product_discovery_candidates WHERE identity_key LIKE ? ORDER BY id").bind(`${prefix}%`).all<{id:number}>()).results.map(row=>Number(row.id));
  const states=ids.flatMap(id=>["yahoo","rakuten"].map(provider=>env.DB.prepare("INSERT INTO product_discovery_provider_state(candidate_id,provider,status,attempt_count,failure_count,last_searched_at,next_search_at,last_error,updated_at,queue_priority_yen) VALUES(?,?, 'pending',0,0,NULL,?,'',?,?)").bind(id,provider,at.toISOString(),at.toISOString(),10000)));
  for(let index=0;index<states.length;index+=100)await env.DB.batch(states.slice(index,index+100));
  await env.DB.prepare("UPDATE product_discovery_queue_meta SET dirty=0,reset_requested=0,provider_signature='yahoo,rakuten',generation=1,quote_count=0,candidate_count=?,canonical_count=0,rebuilt_at=?,updated_at=? WHERE id=1").bind(ids.length,at.toISOString(),at.toISOString()).run();
  const calls:{yahoo:number;rakuten:number}={yahoo:0,rakuten:0};
  vi.stubGlobal("fetch",async(input:RequestInfo|URL)=>{const provider=String(input).includes("shopping.yahooapis.jp")?"yahoo":"rakuten";calls[provider]++;return new Response(JSON.stringify(provider==="yahoo"?{hits:[]}:{items:[]}),{status:200});});
  vi.useFakeTimers();vi.setSystemTime(at);
  try{
   const pending=runProductDiscovery({DB:env.DB,YAHOO_CLIENT_ID:"test",RAKUTEN_APPLICATION_ID:"test",RAKUTEN_ACCESS_KEY:"test"},"scheduled",30,at);
   await vi.runAllTimersAsync();
   const result=await pending;
   expect("searchedPairs" in result ? result.searchedPairs : 0).toBe(12);
   expect(calls).toEqual({yahoo:6,rakuten:6});
   const plan=(await env.DB.prepare("EXPLAIN QUERY PLAN SELECT c.id,s.provider FROM product_discovery_provider_state s JOIN product_discovery_candidates c ON c.id=s.candidate_id WHERE s.provider=? AND s.next_search_at<=? ORDER BY s.next_search_at,s.queue_priority_yen DESC,s.candidate_id LIMIT ?").bind("yahoo",at.toISOString(),6).all<{detail:string}>()).results.map(row=>row.detail).join(" ");
   expect(plan).toContain("COVERING INDEX discovery_provider_due_idx");
   expect(plan).not.toContain("TEMP B-TREE");
   const probe=await env.DB.prepare("SELECT c.id,s.provider FROM product_discovery_provider_state s JOIN product_discovery_candidates c ON c.id=s.candidate_id WHERE s.provider=? AND s.next_search_at<=? ORDER BY s.next_search_at,s.queue_priority_yen DESC,s.candidate_id LIMIT ?").bind("yahoo",at.toISOString(),6).all();
   expect(Number(probe.meta.rows_read??0)).toBeLessThanOrEqual(20);
  }finally{vi.useRealTimers();vi.unstubAllGlobals();}
 });
 it("rebuilds the materialized queue once when marked dirty",async()=>{await env.DB.prepare("DELETE FROM product_discovery_candidates").run();await env.DB.prepare("DELETE FROM buyback_quotes").run();const at=new Date("2031-01-01T00:00:00.000Z");const candidate=await env.DB.prepare(`INSERT INTO product_discovery_candidates(identity_key,canonical_product_id,jan,model_number,product_name,brand,category,condition,attributes_json,best_buyback_price_yen,best_buyback_provider,buyback_provider_count,resolver_status,resolver_confidence,resolver_reason,search_query,target_purchase_price_yen,discovery_ceiling_yen,next_search_at,first_seen_at,last_seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind("queue-test:rebuild",null,null,"M2","Queue rebuild test","Maker","other","new","{}",999999,"store-a",1,"searchable",.99,"model_exact","M2",994999,1000000,at.toISOString(),at.toISOString(),at.toISOString(),at.toISOString()).run(),candidateId=Number(candidate.meta.last_row_id);await markDiscoveryQueueDirty(env.DB,true,at);vi.stubGlobal("fetch",async()=>new Response(JSON.stringify({hits:[]}),{status:200}));try{const result=await runProductDiscovery({DB:env.DB,YAHOO_CLIENT_ID:"test"},"manual",1,at);expect(result.searched).toBe(1);const state=await env.DB.prepare("SELECT status,attempt_count FROM product_discovery_provider_state WHERE candidate_id=? AND provider='yahoo'").bind(candidateId).first<any>();expect(state).toMatchObject({status:"succeeded",attempt_count:1});const meta=await env.DB.prepare("SELECT dirty,generation,candidate_count FROM product_discovery_queue_meta WHERE id=1").first<any>();expect(meta.dirty).toBe(0);expect(meta.generation).toBeGreaterThan(0);}finally{vi.unstubAllGlobals();}});
 it("imports a compact KaitoriX candidate idempotently",async()=>{const e={...env,ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;const payload={date:"2026-09-13",replace:true,candidates:[{jan:"4902370553999",productName:"Console 2 未開封",category:"game_console",condition:"new",msrp:50000,bestBuybackPrice:52000,bestBuybackProvider:"store-a",storeCount:2,stores:[{provider:"store-a",price:52000,fetchedAt:"2026-09-13T00:00:00.000Z"},{provider:"store-b",price:51000,fetchedAt:"2026-09-13T00:01:00.000Z"}]}]};const first=await worker.fetch!(new Request("http://test/admin/kaitorix-csv/import-candidates",{method:"POST",headers:{authorization:"Bearer admin-secret","content-type":"application/json"},body:JSON.stringify(payload)}),e);expect(first.status).toBe(202);const second=await worker.fetch!(new Request("http://test/admin/kaitorix-csv/import-candidates",{method:"POST",headers:{authorization:"Bearer admin-secret","content-type":"application/json"},body:JSON.stringify({...payload,replace:false})}),e);expect(second.status).toBe(202);expect((await env.DB.prepare("SELECT COUNT(*) count FROM buyback_quotes WHERE jan='4902370553999' AND buyback_status='accepting'").first<any>()).count).toBe(1);await buildDiscoveryCandidates(env.DB,new Date("2026-09-13T00:02:00.000Z"));const candidate=await env.DB.prepare("SELECT canonical_product_id,buyback_provider_count FROM product_discovery_candidates WHERE jan='4902370553999'").first<any>();expect(candidate.canonical_product_id).toBeGreaterThan(0);expect(candidate.buyback_provider_count).toBe(2);await ingestListings(env.DB,[{source:"retail-test",externalId:"csv-retail",side:"purchase",title:"Console 2",gtin:"4902370553999",model:"Console 2",variant:"new",priceYen:45000,stock:1,capturedAt:"2026-09-13T00:02:00.000Z"}],new Date("2026-09-13T00:02:00.000Z"));expect((await env.DB.prepare("SELECT COUNT(*) count FROM research_listings WHERE canonical_product_id=? AND side='buyback'").bind(candidate.canonical_product_id).first<any>()).count).toBe(1);});
 it("returns only the latest dashboard opportunity for each canonical product",async()=>{const e={...env,ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;const response=await worker.fetch!(new Request("http://test/api/research/dashboard",{headers:{authorization:"Bearer admin-secret"}}),e);const body=await response.json() as any;const keys=body.opportunities.map((x:any)=>x.canonicalKey);expect(new Set(keys).size).toBe(keys.length);});
 it("exposes structured SKIP reasons and threshold gaps",async()=>{const now=new Date();await runPipeline(env.DB,new MockCollector(),now);const row=await env.DB.prepare("SELECT * FROM research_opportunities WHERE decision='SKIP' ORDER BY id DESC LIMIT 1").first<any>();expect(JSON.parse(row.decision_reasons_json)).toContain("profit_below_threshold");expect(row.required_profit_yen).toBe(5000);expect(row.profit_gap_yen).toBe(Math.max(0,5000-row.market_profit_yen));expect(row.required_confidence).toBe(.95);const e={...env,ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env,response=await worker.fetch!(new Request("http://test/api/research/dashboard",{headers:{authorization:"Bearer admin-secret"}}),e),body=await response.json() as any;expect(body.decisionObservability.today.opportunities).toBeGreaterThan(0);expect(body.decisionObservability.skipReasons.some((x:any)=>x.reason==="profit_below_threshold")).toBe(true);expect(body.decisionObservability.recentSkips[0]).toHaveProperty("profitGap");});
});

describe("Research safety invariants",()=>{
 const fixed=(at:string)=>[
  {source:"fixed-shop",externalId:"p",side:"purchase" as const,title:"Camera X body",url:"https://example.test/camera-x",brand:"Maker",model:"Camera X",variant:"body",manufacturerPartNumber:"CAM-X",priceYen:100000,shippingYen:0,feeYen:0,rewardYen:0,stock:1,capturedAt:at},
  {source:"fixed-buyback",externalId:"b",side:"buyback" as const,title:"Camera X buyback",brand:"Maker",model:"Camera X",variant:"body",manufacturerPartNumber:"CAM-X",priceYen:106000,shippingYen:0,feeYen:0,rewardYen:0,stock:1,capturedAt:at}
 ];
 it("evaluates unchanged prices at 48h without writing duplicate snapshots",async()=>{const start="2026-03-01T00:00:00.000Z";await ingestListings(env.DB,fixed(start),new Date(start));const snapshotsBefore=(await env.DB.prepare("SELECT COUNT(*) count FROM research_price_snapshots").first<any>()).count;const later="2026-03-03T00:00:00.000Z",result=await ingestListings(env.DB,fixed(later),new Date(later));expect(result.snapshots).toBe(0);expect((await env.DB.prepare("SELECT COUNT(*) count FROM research_price_snapshots").first<any>()).count).toBe(snapshotsBefore);const evaluation=await env.DB.prepare("SELECT profit_yen,target_met FROM research_evaluations WHERE horizon_hours=48").first<any>();expect(evaluation.profit_yen).toBe(6000);expect(evaluation.target_met).toBe(1);});
 it("applies fixed sale costs identically to entry and evaluation",async()=>{await env.DB.prepare("UPDATE research_settings SET fees_yen=1000 WHERE id=1").run();const start="2026-03-01T00:00:00.000Z";await ingestListings(env.DB,fixed(start),new Date(start));const later="2026-03-03T00:00:00.000Z";await ingestListings(env.DB,fixed(later),new Date(later));const opp=await env.DB.prepare("SELECT market_profit_yen FROM research_opportunities").first<any>(),evaluation=await env.DB.prepare("SELECT profit_yen FROM research_evaluations WHERE horizon_hours=48").first<any>();expect(opp.market_profit_yen).toBe(5000);expect(evaluation.profit_yen).toBe(5000);});
 it("settles a trade exactly once even when close is retried",async()=>{await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));const trade=await env.DB.prepare("SELECT id FROM research_paper_trades WHERE status='OPEN'").first<any>(),before=await env.DB.prepare("SELECT available_cash_yen FROM research_paper_accounts").first<any>();await env.DB.prepare("UPDATE research_paper_trades SET status='CLOSED',settlement_revenue_yen=108000,closed_at=? WHERE id=? AND status='OPEN'").bind("2026-01-02T00:00:00Z",trade.id).run();await env.DB.prepare("UPDATE research_paper_trades SET status='CLOSED',settlement_revenue_yen=108000,closed_at=? WHERE id=? AND status='OPEN'").bind("2026-01-02T00:00:00Z",trade.id).run();const after=await env.DB.prepare("SELECT available_cash_yen,reserved_cash_yen FROM research_paper_accounts").first<any>(),ledger=await env.DB.prepare("SELECT COUNT(*) count FROM paper_settlement_ledger WHERE trade_id=?").bind(trade.id).first<any>();expect(ledger.count).toBe(1);expect(after.available_cash_yen-before.available_cash_yen).toBe(108000);expect(after.reserved_cash_yen).toBe(0);});
 it("rejects unfunded positions inside the database trigger",async()=>{await env.DB.prepare("UPDATE research_paper_accounts SET available_cash_yen=50000 WHERE id=1").run();await runPipeline(env.DB,new MockCollector(),new Date("2026-01-01T00:00:00Z"));expect((await env.DB.prepare("SELECT COUNT(*) count FROM research_paper_trades").first<any>()).count).toBe(0);expect((await env.DB.prepare("SELECT available_cash_yen FROM research_paper_accounts").first<any>()).available_cash_yen).toBe(50000);});
 it("fails closed when strong canonical aliases disagree",async()=>{const base=fixed("2026-03-01T00:00:00.000Z")[0];await resolveProduct(env.DB,{...base,gtin:"12345678"});await expect(resolveProduct(env.DB,{...base,externalId:"other",gtin:"87654321"})).rejects.toThrow("conflicting GTIN");});
 it("serves the research UI without login and syncs initial capital",async()=>{const e={...env,ADMIN_TOKEN:"admin-secret",COLLECTOR_MODE:"disabled" as const} as Env;const dashboard=await worker.fetch!(new Request("http://test/api/research/dashboard"),e);expect(dashboard.status).toBe(200);const update=await worker.fetch!(new Request("http://test/api/research/settings",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({initialCapital:350000,minimumProfit:5000,minimumConfidence:.95,saleShipping:0,fees:0,evaluationHours:[24,48,72,168],maxPriceAgeMinutes:60})}),e);expect(update.status).toBe(200);const account=await env.DB.prepare("SELECT initial_cash_yen,available_cash_yen FROM research_paper_accounts").first<any>();expect(account.initial_cash_yen).toBe(350000);expect(account.available_cash_yen).toBe(350000);});
 it("does not pair a fresh quote with a stale counterparty",async()=>{const start="2026-03-01T00:00:00.000Z";await ingestListings(env.DB,[fixed(start)[0]],new Date(start));const later="2026-03-01T02:00:00.000Z";await ingestListings(env.DB,[{...fixed(later)[1]}],new Date(later));expect((await env.DB.prepare("SELECT COUNT(*) count FROM research_opportunities").first<any>()).count).toBe(0);});
});
