const number=(value:unknown)=>Number(value??0);

export async function researchAnalytics(db:D1Database){
 const coverage=(await db.prepare(`WITH horizons(hours) AS (VALUES(24),(48),(72),(168)) SELECT h.hours horizon,COUNT(o.id) total,SUM(CASE WHEN e.evaluation_status='completed' THEN 1 ELSE 0 END) completed,SUM(CASE WHEN e.evaluation_status='pending_data' THEN 1 ELSE 0 END) pendingData FROM research_opportunities o CROSS JOIN horizons h LEFT JOIN research_opportunity_evaluations e ON e.opportunity_id=o.id AND e.horizon_hours=h.hours GROUP BY h.hours ORDER BY h.hours`).all<any>()).results;
 const scoreSuccess=(await db.prepare(`WITH scored AS (SELECT CASE WHEN o.sprea_score>=90 THEN '90-100' WHEN o.sprea_score>=80 THEN '80-89' WHEN o.sprea_score>=70 THEN '70-79' ELSE '0-69' END bucket,e.label_48h label FROM research_opportunity_evaluations e JOIN research_opportunities o ON o.id=e.opportunity_id WHERE e.horizon_hours=48 AND e.evaluation_status='completed' AND e.label_48h IS NOT NULL) SELECT bucket,COUNT(*) evaluated,ROUND(AVG(label)*100,1) successRate FROM scored GROUP BY bucket ORDER BY CASE bucket WHEN '90-100' THEN 1 WHEN '80-89' THEN 2 WHEN '70-79' THEN 3 ELSE 4 END`).all<any>()).results;
 const providerRetention=(await db.prepare(`SELECT 'retail' side,l.source provider,e.horizon_hours horizon,COUNT(*) evaluated,ROUND(AVG(e.retail_price_yen*100.0/NULLIF(o.buy_cost_yen,0)),1) retentionRate FROM research_opportunity_evaluations e JOIN research_opportunities o ON o.id=e.opportunity_id JOIN research_listings l ON l.id=o.purchase_listing_id WHERE e.evaluation_status='completed' AND e.retail_price_yen IS NOT NULL GROUP BY l.source,e.horizon_hours UNION ALL SELECT 'buyback' side,l.source provider,e.horizon_hours horizon,COUNT(*) evaluated,ROUND(AVG(e.buyback_price_yen*100.0/NULLIF(o.buyback_price_yen,0)),1) retentionRate FROM research_opportunity_evaluations e JOIN research_opportunities o ON o.id=e.opportunity_id JOIN research_listings l ON l.id=o.buyback_listing_id WHERE e.evaluation_status='completed' AND e.buyback_price_yen IS NOT NULL GROUP BY l.source,e.horizon_hours ORDER BY side,provider,horizon`).all<any>()).results;
 const categories=(await db.prepare(`SELECT COALESCE(NULLIF(p.category,''),'未分類') category,COUNT(*) opportunities,SUM(CASE WHEN o.decision='BUY' THEN 1 ELSE 0 END) buys,ROUND(AVG(o.market_profit_yen),0) averageProfit,MAX(o.market_profit_yen) maximumProfit FROM research_opportunities o JOIN canonical_products p ON p.id=o.canonical_product_id GROUP BY COALESCE(NULLIF(p.category,''),'未分類') ORDER BY maximumProfit DESC`).all<any>()).results;
 const providerGaps=(await db.prepare(`SELECT r.source provider,COUNT(*) listings,COUNT(DISTINCT r.candidate_id) products,ROUND(AVG(MAX(5000-(c.best_buyback_price_yen-r.price_yen),0)),0) averageProfitGap,SUM(CASE WHEN c.best_buyback_price_yen-r.price_yen>=5000 THEN 1 ELSE 0 END) thresholdCount FROM product_discovery_results r JOIN product_discovery_candidates c ON c.id=r.candidate_id GROUP BY r.source ORDER BY averageProfitGap`).all<any>()).results;
 const nearBuy=(await db.prepare(`WITH best AS (SELECT c.id,c.product_name,c.category,c.best_buyback_price_yen,c.best_buyback_provider,r.source retail_provider,r.title,r.price_yen,r.product_url,5000-(c.best_buyback_price_yen-r.price_yen) profit_gap,c.best_buyback_price_yen-r.price_yen estimated_profit,ROW_NUMBER() OVER(PARTITION BY c.id ORDER BY 5000-(c.best_buyback_price_yen-r.price_yen),r.captured_at DESC) rank FROM product_discovery_candidates c JOIN product_discovery_results r ON r.candidate_id=c.id WHERE c.best_buyback_price_yen-r.price_yen<5000) SELECT * FROM best WHERE rank=1 AND profit_gap>0 ORDER BY profit_gap LIMIT 20`).all<any>()).results;
 const beforeAfter=await db.prepare(`WITH ranked AS (SELECT r.candidate_id,c.best_buyback_price_yen,r.price_yen,r.captured_at,ROW_NUMBER() OVER(PARTITION BY r.candidate_id ORDER BY r.captured_at,r.id) first_rank FROM product_discovery_results r JOIN product_discovery_candidates c ON c.id=r.candidate_id), paired AS (SELECT candidate_id,MAX(CASE WHEN first_rank=1 THEN MAX(5000-(best_buyback_price_yen-price_yen),0) END) first_gap,MIN(MAX(5000-(best_buyback_price_yen-price_yen),0)) latest_gap FROM ranked GROUP BY candidate_id) SELECT COUNT(*) products,ROUND(AVG(first_gap),0) beforeAverageGap,ROUND(AVG(latest_gap),0) afterAverageGap,ROUND(AVG(first_gap-latest_gap),0) averageImprovement FROM paired`).first<any>();
 return{evaluationCoverage:coverage.map(row=>({horizon:Number(row.horizon),total:number(row.total),completed:number(row.completed),pendingData:number(row.pendingData)})),scoreSuccess:scoreSuccess.map(row=>({bucket:row.bucket,evaluated:number(row.evaluated),successRate:number(row.successRate)})),providerRetention:providerRetention.map(row=>({side:row.side,provider:row.provider,horizon:number(row.horizon),evaluated:number(row.evaluated),retentionRate:number(row.retentionRate)})),categories:categories.map(row=>({category:row.category,opportunities:number(row.opportunities),buys:number(row.buys),averageProfit:number(row.averageProfit),maximumProfit:number(row.maximumProfit)})),providerProfitGaps:providerGaps.map(row=>({provider:row.provider,listings:number(row.listings),products:number(row.products),averageProfitGap:number(row.averageProfitGap),thresholdCount:number(row.thresholdCount)})),nearBuy:nearBuy.map(row=>({candidateId:number(row.id),productName:row.product_name,category:row.category,retailProvider:row.retail_provider,buybackProvider:row.best_buyback_provider,retailPrice:number(row.price_yen),buybackPrice:number(row.best_buyback_price_yen),estimatedProfit:number(row.estimated_profit),profitGap:number(row.profit_gap),productUrl:row.product_url})),discoveryComparison:{products:number(beforeAfter?.products),beforeAverageGap:number(beforeAfter?.beforeAverageGap),afterAverageGap:number(beforeAfter?.afterAverageGap),averageImprovement:number(beforeAfter?.averageImprovement)}};
}
