import {normalizeModelNumber,normalizeProductName} from "./domain";
import {ingestListings} from "./pipeline";
import type {ListingObservation} from "./types";
import {searchAmazonCreators} from "./collectors/amazon-creators";

type QuoteRow={provider:string;product_name:string;jan:string|null;model_number:string|null;brand:string|null;category:string|null;condition:string;attributes_json:string;price:number;fetched_at:string};
type Candidate={id:number;canonical_product_id:number;jan:string|null;model_number:string|null;product_name:string;brand:string|null;category:string|null;condition:string;attributes_json:string;best_buyback_price_yen:number;search_query:string;discovery_ceiling_yen:number};
type Hit={code?:unknown;name?:unknown;price?:unknown;inStock?:unknown;condition?:unknown;janCode?:unknown;shipping?:{code?:unknown};url?:unknown};
type RakutenItem={itemCode?:unknown;itemName?:unknown;itemCaption?:unknown;catchcopy?:unknown;itemPrice?:unknown;itemUrl?:unknown;availability?:unknown;postageFlag?:unknown;pointRate?:unknown;pointRateEndTime?:unknown};
export type DiscoveryEnv={DB:D1Database;YAHOO_CLIENT_ID?:string;RAKUTEN_APPLICATION_ID?:string;RAKUTEN_ACCESS_KEY?:string;AMAZON_CREATORS_CLIENT_ID?:string;AMAZON_CREATORS_CLIENT_SECRET?:string;AMAZON_PARTNER_TAG?:string};
const validJan=(value:string|null)=>value&&/^\d{8,14}$/.test(value)?value:null;
export function candidateIdentity(row:Pick<QuoteRow,"jan"|"model_number"|"product_name"|"condition"|"attributes_json">):string{const jan=validJan(row.jan);if(jan)return`jan:${jan}:${row.condition}`;const model=normalizeModelNumber(row.model_number);if(model)return`model:${model}:${row.condition}`;return`name:${normalizeProductName(row.product_name)}:${row.attributes_json}:${row.condition}`;}
export function discoveryQuery(input:{jan:string|null;model_number:string|null;product_name:string;attributes_json:string}):string{const model=input.model_number?.trim();if(model)return model;const jan=validJan(input.jan);if(jan)return jan;const attributes=JSON.parse(input.attributes_json||"{}") as Record<string,unknown>,suffix=[attributes.storage,attributes.color,attributes.edition].filter(x=>typeof x==="string").join(" ");return`${input.product_name} ${suffix}`.trim();}
export function purchaseTargets(bestBuyback:number,requiredProfit:number,saleCosts:number,buffer=3000){const target=Math.max(0,bestBuyback-requiredProfit-saleCosts);return{target,ceiling:target+buffer};}
export function rakutenDiscoveryQuery(candidate:Pick<Candidate,"model_number"|"product_name">):string{const model=candidate.model_number?.trim();if(model)return model;const embedded=candidate.product_name.match(/\b(?:[A-Z0-9]{4,}J\/A|CFI[- ]?\d{4}[A-Z]\d{2})\b/i)?.[0];if(embedded)return embedded;return candidate.product_name.normalize("NFKC").replace(/[\[【].*?[\]】]/g," ").replace(/新品|未開封|送料無料|買取価格|SIMフリー/gi," ").replace(/\s+/g," ").trim().slice(0,128);}
export function rakutenDiscoveryQueries(candidate:Pick<Candidate,"model_number"|"product_name">):string[]{const primary=rakutenDiscoveryQuery(candidate),capacity=primary.match(/\b\d+(?:GB|TB)\b/i)?.[0]??"",compact=primary.replace(/\b(iPhone|iPad)\s+(\d+)/i,"$1$2").replace(/\s+(Pro|Max|Air)\b/gi,"$1").replace(/\s+\d+(?:GB|TB)\b.*$/i,"").trim(),fallback=[compact,capacity].filter(Boolean).join(" ");return[...new Set([primary,fallback,compact].filter(Boolean))];}
const normalizedAttribute=(value:unknown)=>typeof value==="string"?value.normalize("NFKC").toLowerCase().replace(/[\s\-_]/g,""):"";
export function rakutenIdentityMatches(candidate:Pick<Candidate,"jan"|"model_number"|"product_name"|"attributes_json">,item:Pick<RakutenItem,"itemName"|"itemCaption"|"catchcopy">){const text=[item.itemName,item.catchcopy,item.itemCaption].filter(x=>typeof x==="string").join(" "),normalized=normalizeModelNumber(text),model=normalizeModelNumber(candidate.model_number);if(/中古|整備済|再生品|訳あり|ジャンク|海外版/i.test(text))return false;if(model)return normalized.includes(model);if(candidate.jan&&text.replace(/\D/g,"").includes(candidate.jan))return true;const name=normalizeProductName(candidate.product_name),title=normalizeProductName(text),compactTitle=title.replace(/\s/g,"");if(!name)return false;const tokens=name.split(/\s+/).map(value=>value.replace(/[^a-z0-9一-龠ぁ-んァ-ヶ]/gi,"")).filter(value=>value.length>1&&!/^(apple|simフリー|国内版|本体|モデル)$/.test(value));if(tokens.length<2||!tokens.every(value=>compactTitle.includes(value.replace(/\s/g,""))))return false;const attributes=JSON.parse(candidate.attributes_json||"{}") as Record<string,unknown>;return[attributes.storage,attributes.color,attributes.edition].filter(Boolean).every(value=>compactTitle.includes(normalizedAttribute(value)));}

async function promote(db:D1Database,row:QuoteRow,identity:string,at:string):Promise<number|null>{const jan=validJan(row.jan);if(!jan&&!normalizeModelNumber(row.model_number))return null;const aliasType=jan?"gtin":"mpn",aliasValue=jan??`${normalizeModelNumber(row.model_number)}:`;const existing=await db.prepare("SELECT canonical_product_id FROM canonical_product_aliases WHERE alias_type=? AND alias_value=? AND condition=?").bind(aliasType,aliasValue,row.condition).first<{canonical_product_id:number}>();if(existing)return existing.canonical_product_id;const key=jan?`gtin:${jan}:${row.condition}`:`mpn:${aliasValue}:${row.condition}`;await db.prepare(`INSERT INTO canonical_products(canonical_key,gtin,manufacturer_part_number,brand,model,variant,category,capacity,color,condition,title,created_at,updated_at) VALUES(?,?,?,?,?,'',?,'','',?,?,?,?) ON CONFLICT(canonical_key) DO NOTHING`).bind(key,jan,row.model_number,row.brand??"",row.product_name,row.category??"",row.condition,row.product_name,at,at).run();const product=await db.prepare("SELECT id FROM canonical_products WHERE canonical_key=?").bind(key).first<{id:number}>();if(!product)return null;await db.prepare("INSERT OR IGNORE INTO canonical_product_aliases(alias_type,alias_value,condition,canonical_product_id,created_at) VALUES(?,?,?,?,?)").bind(aliasType,aliasValue,row.condition,product.id,at).run();return product.id;}

export async function buildDiscoveryCandidates(db:D1Database,at=new Date()):Promise<{quotes:number;candidates:number;canonical:number}>{
 const rows=(await db.prepare(`WITH latest AS (SELECT *,ROW_NUMBER() OVER(PARTITION BY provider,COALESCE(external_id,id) ORDER BY fetched_at DESC,id DESC) rank FROM buyback_quotes) SELECT provider,product_name,jan,model_number,brand,category,condition,attributes_json,price,fetched_at FROM latest WHERE rank=1 AND buyback_status='accepting' AND condition IN ('new','unused') AND price>0`).all<QuoteRow>()).results;
 const groups=new Map<string,QuoteRow[]>();for(const row of rows){const key=candidateIdentity(row),items=groups.get(key)??[];items.push(row);groups.set(key,items);}
 const aliases=(await db.prepare("SELECT alias_type,alias_value,condition,canonical_product_id FROM canonical_product_aliases WHERE alias_type IN ('gtin','mpn')").all<any>()).results,aliasMap=new Map(aliases.map(row=>[`${row.alias_type}:${row.alias_value}:${row.condition}`,Number(row.canonical_product_id)]));
 const missing:[string,QuoteRow,string,string][]=[];for(const[identity,items]of groups){const best=[...items].sort((a,b)=>b.price-a.price)[0],jan=validJan(best.jan),model=normalizeModelNumber(best.model_number),aliasType=jan?"gtin":"mpn",aliasValue=jan??`${model}:`;if((jan||model)&&!aliasMap.has(`${aliasType}:${aliasValue}:${best.condition}`))missing.push([identity,best,aliasType,aliasValue]);}
 if(missing.length)await db.batch(missing.map(([,row,,])=>{const jan=validJan(row.jan),model=normalizeModelNumber(row.model_number),key=jan?`gtin:${jan}:${row.condition}`:`mpn:${model}::${row.condition}`;return db.prepare(`INSERT INTO canonical_products(canonical_key,gtin,manufacturer_part_number,brand,model,variant,category,capacity,color,condition,title,created_at,updated_at) VALUES(?,?,?,?,?,'',?,'','',?,?,?,?) ON CONFLICT(canonical_key) DO NOTHING`).bind(key,jan,row.model_number,row.brand??"",row.product_name,row.category??"",row.condition,row.product_name,at.toISOString(),at.toISOString());}));
 const products=(await db.prepare("SELECT id,canonical_key FROM canonical_products").all<any>()).results,productByKey=new Map(products.map(row=>[String(row.canonical_key),Number(row.id)])),aliasStatements:D1PreparedStatement[]=[];
 for(const[,row,aliasType,aliasValue]of missing){const jan=validJan(row.jan),model=normalizeModelNumber(row.model_number),key=jan?`gtin:${jan}:${row.condition}`:`mpn:${model}::${row.condition}`,productId=productByKey.get(key);if(productId){aliasMap.set(`${aliasType}:${aliasValue}:${row.condition}`,productId);aliasStatements.push(db.prepare("INSERT OR IGNORE INTO canonical_product_aliases(alias_type,alias_value,condition,canonical_product_id,created_at) VALUES(?,?,?,?,?)").bind(aliasType,aliasValue,row.condition,productId,at.toISOString()));}}
 if(aliasStatements.length)await db.batch(aliasStatements);
 const config=await db.prepare("SELECT minimum_profit_yen,sale_shipping_yen,fees_yen FROM research_settings WHERE id=1").first<any>(),candidateStatements:D1PreparedStatement[]=[];let canonical=0;
 for(const[identity,items]of groups){const best=[...items].sort((a,b)=>b.price-a.price)[0],jan=validJan(best.jan),model=normalizeModelNumber(best.model_number),aliasType=jan?"gtin":"mpn",aliasValue=jan??`${model}:`,productId=(jan||model)?aliasMap.get(`${aliasType}:${aliasValue}:${best.condition}`)??null:null;if(productId)canonical++;const providers=new Set(items.map(x=>x.provider)),targets=purchaseTargets(best.price,config.minimum_profit_yen,config.sale_shipping_yen+config.fees_yen),query=discoveryQuery(best);candidateStatements.push(db.prepare(`INSERT INTO product_discovery_candidates(identity_key,canonical_product_id,jan,model_number,product_name,brand,category,condition,attributes_json,best_buyback_price_yen,best_buyback_provider,buyback_provider_count,resolver_status,resolver_confidence,resolver_reason,search_query,target_purchase_price_yen,discovery_ceiling_yen,next_search_at,first_seen_at,last_seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(identity_key) DO UPDATE SET canonical_product_id=excluded.canonical_product_id,product_name=excluded.product_name,best_buyback_price_yen=excluded.best_buyback_price_yen,best_buyback_provider=excluded.best_buyback_provider,buyback_provider_count=excluded.buyback_provider_count,resolver_status=CASE WHEN product_discovery_candidates.resolver_status='retail_found' THEN 'retail_found' ELSE excluded.resolver_status END,resolver_confidence=excluded.resolver_confidence,resolver_reason=excluded.resolver_reason,search_query=excluded.search_query,target_purchase_price_yen=excluded.target_purchase_price_yen,discovery_ceiling_yen=excluded.discovery_ceiling_yen,last_seen_at=excluded.last_seen_at,updated_at=excluded.updated_at`).bind(identity,productId,best.jan,best.model_number,best.product_name,best.brand,best.category,best.condition,best.attributes_json,best.price,best.provider,providers.size,productId?"searchable":"unresolved",productId?(jan?1:.99):0,productId?(jan?"jan_exact":"model_exact"):"identity_insufficient",query,targets.target,targets.ceiling,at.toISOString(),at.toISOString(),at.toISOString(),at.toISOString()));}
 for(let index=0;index<candidateStatements.length;index+=100)await db.batch(candidateStatements.slice(index,index+100));return{quotes:rows.length,candidates:groups.size,canonical};
}
async function yahoo(candidate:Candidate,clientId:string,at:Date):Promise<ListingObservation[]>{const url=new URL("https://shopping.yahooapis.jp/ShoppingWebService/V3/itemSearch");url.searchParams.set("appid",clientId);url.searchParams.set("query",candidate.search_query);url.searchParams.set("results","20");url.searchParams.set("condition","new");url.searchParams.set("in_stock","true");url.searchParams.set("sort","+price");const response=await fetch(url,{headers:{accept:"application/json"}});if(!response.ok)throw new Error(`Yahoo discovery failed (${response.status})`);const payload=await response.json() as{hits?:Hit[]},expectedModel=normalizeModelNumber(candidate.model_number),results:ListingObservation[]=[];for(const hit of payload.hits??[]){const title=typeof hit.name==="string"?hit.name:"",jan=typeof hit.janCode==="string"?hit.janCode:null,price=Number(hit.price),externalId=typeof hit.code==="string"?hit.code:"",productUrl=typeof hit.url==="string"?hit.url:"";const identityMatches=candidate.jan?(jan===candidate.jan):expectedModel?normalizeModelNumber(title).includes(expectedModel):false;if(!identityMatches||!Number.isSafeInteger(price)||price<=0||!externalId||!productUrl||hit.condition!=="new"||hit.inStock!==true||Number(hit.shipping?.code)!==2)continue;results.push({source:"yahoo-discovery",externalId,side:"purchase",title,url:productUrl,gtin:candidate.jan??undefined,manufacturerPartNumber:candidate.model_number??undefined,brand:candidate.brand??undefined,model:candidate.product_name,category:candidate.category??undefined,condition:"new",priceYen:price,shippingYen:0,feeYen:0,rewardYen:0,stock:1,stockStatus:"in_stock",purchasable:true,capturedAt:at.toISOString(),raw:hit});}return results.sort((a,b)=>a.priceYen-b.priceYen).slice(0,10);}

export async function searchRakuten(candidate:Candidate,applicationId:string,accessKey:string,at:Date,fetcher:typeof fetch=fetch,sleeper:(ms:number)=>Promise<void>=ms=>new Promise(resolve=>setTimeout(resolve,ms))):Promise<ListingObservation[]>{
 const url=new URL("https://openapi.rakuten.co.jp/ichibams/api/IchibaItem/Search/20260701");
 url.searchParams.set("applicationId",applicationId);url.searchParams.set("hits","30");url.searchParams.set("format","json");url.searchParams.set("formatVersion","2");url.searchParams.set("availability","1");
 let rawItems:Array<RakutenItem|{item?:RakutenItem}>=[],usedQuery="";const queries=rakutenDiscoveryQueries(candidate);for(let queryIndex=0;queryIndex<queries.length;queryIndex++){usedQuery=queries[queryIndex];url.searchParams.set("keyword",usedQuery);let response:Response|undefined;for(let attempt=0;attempt<3;attempt++){response=await fetcher(url,{headers:{accessKey,accept:"application/json",origin:"https://sprea-frontend.pages.dev",referer:"https://sprea-frontend.pages.dev/"}});if(response.ok||![429,500,502,503,504].includes(response.status))break;if(attempt<2)await sleeper(1000*2**attempt);}if(!response?.ok)throw new Error(`Rakuten discovery failed (${response?.status??"network"})`);const payload=await response.json() as{items?:Array<RakutenItem|{item?:RakutenItem}>};rawItems=payload.items??[];if(rawItems.length)break;if(queryIndex<queries.length-1)await sleeper(1100);}
 const results:ListingObservation[]=[];let identityMatches=0,eligible=0;
 for(const wrapped of rawItems){const item="item" in wrapped&&wrapped.item?wrapped.item:wrapped as RakutenItem,title=typeof item.itemName==="string"?item.itemName:"",price=Number(item.itemPrice),externalId=typeof item.itemCode==="string"?item.itemCode:"",productUrl=typeof item.itemUrl==="string"?item.itemUrl:"",pointRate=Number(item.pointRate),reward=Number.isFinite(pointRate)&&pointRate>0&&typeof item.pointRateEndTime==="string"&&Date.parse(item.pointRateEndTime)>at.getTime()+24*3_600_000?Math.floor(price*pointRate/100):0;if(!rakutenIdentityMatches(candidate,item))continue;identityMatches++;if(!Number.isSafeInteger(price)||price<=0||!externalId||!productUrl||Number(item.availability)!==1||Number(item.postageFlag)!==0)continue;eligible++;results.push({source:"rakuten-discovery",externalId,side:"purchase",title,url:productUrl,gtin:candidate.jan??undefined,manufacturerPartNumber:candidate.model_number??undefined,brand:candidate.brand??undefined,model:candidate.product_name,category:candidate.category??undefined,condition:"new",priceYen:price,shippingYen:0,feeYen:0,rewardYen:reward,stock:1,stockStatus:"in_stock",purchasable:true,capturedAt:at.toISOString(),raw:item});}console.info("Rakuten discovery summary",{candidateId:candidate.id,query:usedQuery,returned:rawItems.length,identityMatches,eligible});
 return results.sort((a,b)=>a.priceYen-b.priceYen).slice(0,10);
}

export async function runProductDiscovery(env:DiscoveryEnv,trigger="manual",limit=10,at=new Date()){
 const providers=new Map<string,(candidate:Candidate)=>Promise<ListingObservation[]>>();if(env.YAHOO_CLIENT_ID)providers.set("yahoo",candidate=>yahoo(candidate,env.YAHOO_CLIENT_ID!,at));if(env.RAKUTEN_APPLICATION_ID&&env.RAKUTEN_ACCESS_KEY)providers.set("rakuten",candidate=>searchRakuten(candidate,env.RAKUTEN_APPLICATION_ID!,env.RAKUTEN_ACCESS_KEY!,at));if(env.AMAZON_CREATORS_CLIENT_ID&&env.AMAZON_CREATORS_CLIENT_SECRET&&env.AMAZON_PARTNER_TAG)providers.set("amazon",candidate=>searchAmazonCreators(candidate,{clientId:env.AMAZON_CREATORS_CLIENT_ID!,clientSecret:env.AMAZON_CREATORS_CLIENT_SECRET!,partnerTag:env.AMAZON_PARTNER_TAG!},at));if(!providers.size)throw new Error("At least one retail discovery provider is required");
 await env.DB.prepare("UPDATE product_discovery_runs SET status='failed',message='interrupted before completion',finished_at=? WHERE status='running' AND started_at<?").bind(at.toISOString(),new Date(at.getTime()-10*60_000).toISOString()).run();const built=await buildDiscoveryCandidates(env.DB,at),insert=await env.DB.prepare("INSERT INTO product_discovery_runs(trigger,status,quote_count,candidate_count,canonical_count,started_at) VALUES(?,'running',?,?,?,?)").bind(trigger,built.quotes,built.candidates,built.canonical,at.toISOString()).run(),runId=Number(insert.meta.last_row_id);
 const searchable=(await env.DB.prepare("SELECT id FROM product_discovery_candidates WHERE resolver_status IN ('searchable','retail_found')").all<{id:number}>()).results,initializers:D1PreparedStatement[]=[];for(const candidate of searchable)for(const provider of providers.keys())initializers.push(env.DB.prepare("INSERT OR IGNORE INTO product_discovery_provider_state(candidate_id,provider,next_search_at,updated_at) VALUES(?,?,?,?)").bind(candidate.id,provider,at.toISOString(),at.toISOString()));for(let i=0;i<initializers.length;i+=100)await env.DB.batch(initializers.slice(i,i+100));
 const names=[...providers.keys()],placeholders=names.map(()=>"?").join(","),pairs=(await env.DB.prepare(`SELECT c.*,s.provider FROM product_discovery_provider_state s JOIN product_discovery_candidates c ON c.id=s.candidate_id WHERE s.provider IN (${placeholders}) AND (s.next_search_at IS NULL OR s.next_search_at<=?) AND c.resolver_status IN ('searchable','retail_found') ORDER BY c.buyback_provider_count DESC,c.best_buyback_price_yen DESC,s.last_searched_at LIMIT ?`).bind(...names,at.toISOString(),Math.max(1,Math.min(100,limit))).all<Candidate&{provider:string}>()).results;
 let purchasable=0,profitable=0,threshold=0,buys=0,failures=0;const foundCandidates=new Set<number>(),searchedCandidates=new Set<number>(),providerStats:Record<string,{searched:number;found:number;listings:number;profitable:number;threshold:number;failures:number}>={},lastRequest=new Map<string,number>();for(const name of names)providerStats[name]={searched:0,found:0,listings:0,profitable:0,threshold:0,failures:0};
 for(const pair of pairs){searchedCandidates.add(pair.id);const stats=providerStats[pair.provider],search=providers.get(pair.provider)!;stats.searched++;try{if(pair.provider==="rakuten"){const wait=Math.max(0,1100-(Date.now()-(lastRequest.get("rakuten")??0)));if(wait)await new Promise(resolve=>setTimeout(resolve,wait));lastRequest.set("rakuten",Date.now());}const listings=await search(pair);if(listings.length){stats.found++;foundCandidates.add(pair.id);}stats.listings+=listings.length;purchasable+=listings.length;for(const listing of listings){const profit=pair.best_buyback_price_yen-listing.priceYen+(listing.rewardYen??0);if(profit>0){profitable++;stats.profitable++;}if(profit>=5000){threshold++;stats.threshold++;}await env.DB.prepare("INSERT OR IGNORE INTO product_discovery_results(run_id,candidate_id,source,external_id,title,price_yen,product_url,within_discovery_ceiling,captured_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(runId,pair.id,listing.source,listing.externalId,listing.title,listing.priceYen,listing.url,listing.priceYen-(listing.rewardYen??0)<=pair.discovery_ceiling_yen?1:0,at.toISOString()).run();}if(listings.length){const summary=await ingestListings(env.DB,listings,at);buys+=summary.buys;await env.DB.prepare("UPDATE product_discovery_candidates SET resolver_status='retail_found',updated_at=? WHERE id=?").bind(at.toISOString(),pair.id).run();}await env.DB.prepare("UPDATE product_discovery_provider_state SET status='succeeded',attempt_count=attempt_count+1,last_searched_at=?,next_search_at=?,last_error='',updated_at=? WHERE candidate_id=? AND provider=?").bind(at.toISOString(),new Date(at.getTime()+6*3_600_000).toISOString(),at.toISOString(),pair.id,pair.provider).run();}catch(error){failures++;stats.failures++;await env.DB.prepare("UPDATE product_discovery_provider_state SET status='failed',attempt_count=attempt_count+1,failure_count=failure_count+1,last_searched_at=?,next_search_at=?,last_error=?,updated_at=? WHERE candidate_id=? AND provider=?").bind(at.toISOString(),new Date(at.getTime()+60*60_000).toISOString(),error instanceof Error?error.message.slice(0,500):"search failed",at.toISOString(),pair.id,pair.provider).run();}}
 for(const[name,stats]of Object.entries(providerStats))await env.DB.prepare("INSERT INTO product_discovery_provider_runs(run_id,provider,searched_count,found_count,listing_count,profitable_count,threshold_count,failure_count) VALUES(?,?,?,?,?,?,?,?)").bind(runId,name,stats.searched,stats.found,stats.listings,stats.profitable,stats.threshold,stats.failures).run();const status=failures===pairs.length&&pairs.length?"failed":"succeeded";await env.DB.prepare("UPDATE product_discovery_runs SET status=?,searched_count=?,yahoo_found_count=?,purchasable_count=?,profitable_count=?,threshold_count=?,buy_count=?,failure_count=?,message=?,finished_at=? WHERE id=?").bind(status,searchedCandidates.size,foundCandidates.size,purchasable,profitable,threshold,buys,failures,`searched ${pairs.length} candidate/provider pairs`,new Date().toISOString(),runId).run();return{runId,...built,searched:searchedCandidates.size,retailFound:foundCandidates.size,yahooFound:foundCandidates.size,purchasable,profitable,threshold,buys,failures,providers:providerStats};
}

export async function discoveryFunnel(db:D1Database){const totals=await db.prepare(`SELECT (SELECT COUNT(*) FROM buyback_quotes) buybackQuotes,(SELECT COUNT(*) FROM product_discovery_candidates) candidates,(SELECT COUNT(*) FROM product_discovery_candidates WHERE canonical_product_id IS NOT NULL) canonicalProducts,(SELECT COUNT(DISTINCT candidate_id) FROM product_discovery_results) yahooFound,(SELECT COUNT(*) FROM product_discovery_results) purchasable,(SELECT COUNT(*) FROM product_discovery_results r JOIN product_discovery_candidates c ON c.id=r.candidate_id WHERE c.best_buyback_price_yen-r.price_yen>0) profitable,(SELECT COUNT(*) FROM product_discovery_results r JOIN product_discovery_candidates c ON c.id=r.candidate_id WHERE c.best_buyback_price_yen-r.price_yen>=5000) threshold,(SELECT COUNT(*) FROM research_opportunities WHERE decision='BUY') buys`).first<any>(),run=await db.prepare("SELECT * FROM product_discovery_runs ORDER BY id DESC LIMIT 1").first<any>(),providers=(await db.prepare(`SELECT r.source provider,COUNT(DISTINCT r.candidate_id) found,COUNT(*) listings,SUM(CASE WHEN c.best_buyback_price_yen-r.price_yen>0 THEN 1 ELSE 0 END) profitable,SUM(CASE WHEN c.best_buyback_price_yen-r.price_yen>=5000 THEN 1 ELSE 0 END) threshold,AVG(MAX(5000-(c.best_buyback_price_yen-r.price_yen),0)) averageProfitGap FROM product_discovery_results r JOIN product_discovery_candidates c ON c.id=r.candidate_id GROUP BY r.source`).all<any>()).results,latestRuns=run?(await db.prepare("SELECT * FROM product_discovery_provider_runs WHERE run_id=?").bind(run.id).all<any>()).results:[];return{buybackQuotes:Number(totals?.buybackQuotes??0),candidates:Number(totals?.candidates??0),canonicalProducts:Number(totals?.canonicalProducts??0),yahooFound:Number(totals?.yahooFound??0),purchasable:Number(totals?.purchasable??0),profitable:Number(totals?.profitable??0),threshold:Number(totals?.threshold??0),buys:Number(totals?.buys??0),providers:providers.map(row=>({...row,found:Number(row.found),listings:Number(row.listings),profitable:Number(row.profitable),threshold:Number(row.threshold),averageProfitGap:Number(row.averageProfitGap)})),lastProviderRuns:latestRuns,lastRun:run??null};}
