import {MockCollector} from "./mock-collector";
import {collectorFromEnv} from "./collectors";
import {createBuybackQuoteOpportunities,evaluateDue,ingestListings,runPipeline} from "./pipeline";
import type {IngestPayload,ListingObservation} from "./types";
import {ImportBuybackQuotes} from "./application/import-buyback-quotes";
import {D1BuybackQuoteRepository} from "./infrastructure/d1-buyback-quote-repository";
import {D1ProductResolver} from "./infrastructure/d1-product-resolver";
import {discoveryFunnel,runProductDiscovery} from "./discovery";

const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8"}});
const isAuthorized=(r:Request,token?:string)=>Boolean(token)&&r.headers.get("authorization")===`Bearer ${token}`;
const limit=(u:URL,fallback=100)=>Math.max(1,Math.min(500,Number.parseInt(u.searchParams.get("limit")||String(fallback),10)||fallback));
const validTime=(x:unknown)=>typeof x==="string"&&!Number.isNaN(Date.parse(x));
const validListing=(x:unknown):x is ListingObservation=>{if(!x||typeof x!=="object")return false;const o=x as Record<string,unknown>;return ["source","externalId","title","model","capturedAt"].every(k=>typeof o[k]==="string"&&String(o[k]).trim().length>0)&&["purchase","buyback"].includes(String(o.side))&&Number.isInteger(o.priceYen)&&Number(o.priceYen)>=0&&Number.isInteger(o.stock)&&Number(o.stock)>=0&&validTime(o.capturedAt)&&(o.stockStatus===undefined||["in_stock","low_stock","out_of_stock","preorder","unknown"].includes(String(o.stockStatus)))&&["shippingYen","feeYen","rewardYen"].every(k=>o[k]===undefined||(Number.isInteger(o[k])&&Number(o[k])>=0));};
const normalizeWireListing=(value:unknown):unknown=>{if(!value||typeof value!=="object")return value;const o=value as Record<string,unknown>;if(o.side!==undefined||o.priceYen!==undefined)return value;const attributes=o.attributes&&typeof o.attributes==="object"?o.attributes as Record<string,unknown>:{};const sourceType=o.sourceType;return{source:o.source,externalId:o.externalId,side:sourceType==="retailer"?"purchase":sourceType==="buyback"?"buyback":sourceType,title:o.productName,url:o.productUrl,gtin:o.jan,manufacturerPartNumber:o.modelNumber,brand:o.brand,model:o.modelNumber||o.productName,variant:typeof attributes.variant==="string"?attributes.variant:typeof attributes.storage==="string"?attributes.storage:typeof attributes.edition==="string"?attributes.edition:undefined,category:o.category,capacity:typeof attributes.storage==="string"?attributes.storage:undefined,color:typeof attributes.color==="string"?attributes.color:undefined,condition:o.condition,priceYen:o.price,shippingYen:o.shippingFee,feeYen:o.fee,rewardYen:o.reward,stock:o.stock,stockStatus:o.stockStatus,purchasable:o.purchasable,capturedAt:o.fetchedAt,raw:{attributes}};};

async function dashboard(db:D1Database){
 const account=await db.prepare("SELECT * FROM research_paper_accounts WHERE id=1").first<any>();
 const opportunities=(await db.prepare(`WITH eligible AS (SELECT o.*,p.canonical_key,p.title,p.category,pl.source purchase_source,bl.source buyback_source,pp.stock_status,MAX(pp.captured_at,bp.captured_at) last_updated,ROW_NUMBER() OVER(PARTITION BY o.canonical_product_id ORDER BY o.sprea_score DESC,o.market_profit_yen DESC,o.detected_at DESC,o.id DESC) rank FROM research_opportunities o JOIN canonical_products p ON p.id=o.canonical_product_id JOIN research_listings pl ON pl.id=o.purchase_listing_id JOIN latest_prices pp ON pp.listing_id=pl.id JOIN research_listings bl ON bl.id=o.buyback_listing_id JOIN latest_prices bp ON bp.listing_id=bl.id WHERE o.decision='BUY' AND o.resolver_confidence>=0.95 AND pp.stock_status IN ('in_stock','low_stock') AND pp.price_yen>0 AND pl.url LIKE 'http%' AND pp.captured_at>datetime('now','-120 minutes') AND bp.stock>0 AND bp.price_yen>0 AND bp.captured_at>datetime('now','-180 minutes')) SELECT * FROM eligible WHERE rank=1 ORDER BY sprea_score DESC,market_profit_yen DESC,detected_at DESC LIMIT 100`).all<any>()).results;
 const decisions=opportunities.map(x=>({id:x.id,canonicalKey:x.canonical_key,decision:x.decision.toLowerCase(),reason:x.reason,strategy:"precision-first-baseline",entryProfit:x.market_profit_yen,spreaScore:x.sprea_score,decidedAt:x.detected_at}));
 const e=(await db.prepare("SELECT outcome,market_profit_yen FROM research_opportunity_evaluations WHERE horizon_hours=48 AND evaluation_status='completed'").all<any>()).results,tp=e.filter(x=>x.outcome==="buy_correct").length,fp=e.filter(x=>x.outcome==="buy_failed").length,fn=e.filter(x=>x.outcome==="missed_opportunity").length,bought=e.filter(x=>String(x.outcome).startsWith("buy_"));
 const today=await db.prepare(`SELECT COUNT(*) opportunities,SUM(CASE WHEN decision='BUY' THEN 1 ELSE 0 END) buys,SUM(CASE WHEN decision='SKIP' THEN 1 ELSE 0 END) skips,AVG(CASE WHEN decision='SKIP' THEN profit_gap_yen END) average_profit_gap_yen,MAX(CASE WHEN decision='SKIP' THEN market_profit_yen END) closest_skip_profit_yen FROM research_opportunities WHERE date(detected_at,'+9 hours')=date('now','+9 hours')`).first<any>();
 const skipReasons=(await db.prepare(`SELECT reason.value reason,COUNT(*) count FROM research_opportunities o,json_each(o.decision_reasons_json) reason WHERE o.decision='SKIP' AND date(o.detected_at,'+9 hours')=date('now','+9 hours') GROUP BY reason.value ORDER BY count DESC,reason.value`).all<any>()).results;
 const recentSkips=(await db.prepare(`SELECT o.id,p.canonical_key,p.title,o.market_profit_yen,o.required_profit_yen,o.profit_gap_yen,o.resolver_confidence,o.required_confidence,o.confidence_gap,o.decision_reasons_json,o.detected_at FROM research_opportunities o JOIN canonical_products p ON p.id=o.canonical_product_id WHERE o.decision='SKIP' ORDER BY o.detected_at DESC,o.id DESC LIMIT 20`).all<any>()).results;
 const discovery=await discoveryFunnel(db);
 return{portfolio:{initialCapital:account?.initial_cash_yen??300000,lockedCapital:account?.reserved_cash_yen??0,availableCash:account?.available_cash_yen??300000,openTrades:(await db.prepare("SELECT COUNT(*) count FROM research_paper_trades WHERE status='OPEN'").first<any>())?.count??0},opportunities:opportunities.map(x=>({canonicalKey:x.canonical_key,title:x.title,category:x.category,purchaseSource:x.purchase_source,buybackSource:x.buyback_source,bestBuybackProvider:x.best_buyback_provider??x.buyback_source,purchasePrice:x.purchase_price_yen,purchaseShipping:x.purchase_shipping_yen,buybackPrice:x.buyback_price_yen,bestBuybackPrice:x.buyback_price_yen,marketProfit:x.market_profit_yen,profitRate:x.profit_rate,buybackStoreCount:x.buyback_store_count,secondBuybackProvider:x.second_buyback_provider??null,secondBuybackPrice:x.second_buyback_price_yen??null,thirdBuybackProvider:x.third_buyback_provider??null,thirdBuybackPrice:x.third_buyback_price_yen??null,bestSecondSpread:x.best_second_spread_yen??null,topTwoSpreadRate:x.top_two_spread_rate??0,return30Days:0,spreaScore:x.sprea_score,scoreVersion:x.score_version,scoreReason:JSON.parse(x.score_reason_json||"{}"),stockStatus:x.stock_status,lastUpdated:x.last_updated,detectedAt:x.detected_at})),decisions,discoveryFunnel:discovery,decisionObservability:{today:{opportunities:Number(today?.opportunities??0),buys:Number(today?.buys??0),skips:Number(today?.skips??0)},skipReasons:skipReasons.map(x=>({reason:String(x.reason),count:Number(x.count)})),averageProfitGap:Number(today?.average_profit_gap_yen??0),closestSkipProfit:today?.closest_skip_profit_yen==null?null:Number(today.closest_skip_profit_yen),recentSkips:recentSkips.map(x=>({id:x.id,canonicalKey:x.canonical_key,title:x.title,profit:x.market_profit_yen,requiredProfit:x.required_profit_yen,profitGap:x.profit_gap_yen,confidence:x.resolver_confidence,requiredConfidence:x.required_confidence,confidenceGap:x.confidence_gap,reasons:JSON.parse(x.decision_reasons_json||"[]"),detectedAt:x.detected_at}))},metrics48h:{evaluated:e.length,buyCount:bought.length,precision:tp+fp?tp/(tp+fp):0,recall:tp+fn?tp/(tp+fn):0,missedOpportunities:fn,averageProfit:bought.length?bought.reduce((s,x)=>s+x.market_profit_yen,0)/bought.length:0,maximumLoss:bought.length?Math.min(...bought.map(x=>x.market_profit_yen)):0}};
}
async function productDetail(db:D1Database,key:string){const p=await db.prepare("SELECT * FROM canonical_products WHERE canonical_key=?").bind(key).first<any>();if(!p)return null;const history=(await db.prepare(`SELECT l.source,l.side,s.price_yen,s.stock,s.captured_at,l.resolver_confidence,l.match_reason FROM research_price_snapshots s JOIN research_listings l ON l.id=s.listing_id WHERE l.canonical_product_id=? ORDER BY s.captured_at DESC LIMIT 500`).bind(p.id).all<any>()).results;const decisions=(await db.prepare("SELECT id,decision,reason,market_profit_yen,sprea_score,detected_at FROM research_opportunities WHERE canonical_product_id=? ORDER BY detected_at DESC").bind(p.id).all<any>()).results;const evaluations=(await db.prepare(`SELECT e.*,o.id decision_id FROM research_opportunity_evaluations e JOIN research_opportunities o ON o.id=e.opportunity_id WHERE o.canonical_product_id=? ORDER BY e.checked_at DESC`).bind(p.id).all<any>()).results;return{canonicalKey:p.canonical_key,title:p.title,jan:p.gtin??"",model:p.model,capacity:p.capacity,color:p.color,history:history.map(x=>({source:x.source,side:x.side,price:x.price_yen,stock:x.stock>0,capturedAt:x.captured_at,confidence:x.resolver_confidence,matchReason:x.match_reason})),decisions:decisions.map(x=>({id:x.id,canonicalKey:key,decision:x.decision.toLowerCase(),reason:x.reason,strategy:"precision-first-baseline",entryProfit:x.market_profit_yen,spreaScore:x.sprea_score,decidedAt:x.detected_at})),evaluations:evaluations.map(x=>({decisionId:x.decision_id,horizonHours:x.horizon_hours,status:x.evaluation_status,retailPrice:x.retail_price_yen,buybackPrice:x.buyback_price_yen,profit:x.market_profit_yen,decay:x.decay_yen,decayRate:x.decay_rate,label48h:x.label_48h,outcome:x.outcome,evaluatedAt:x.evaluated_at}))};}
async function listTrades(db:D1Database){const rows=(await db.prepare(`SELECT t.*,o.buy_cost_yen,o.buyback_price_yen,o.market_profit_yen,p.canonical_key,p.title,pl.source purchase_source,bl.source buyback_source FROM research_paper_trades t JOIN research_opportunities o ON o.id=t.opportunity_id JOIN canonical_products p ON p.id=o.canonical_product_id JOIN research_listings pl ON pl.id=o.purchase_listing_id JOIN research_listings bl ON bl.id=o.buyback_listing_id ORDER BY t.opened_at DESC`).all<any>()).results;return rows.map(x=>({id:x.id,canonicalKey:x.canonical_key,title:x.title,purchaseSource:x.purchase_source,buybackSource:x.buyback_source,purchasePrice:x.buy_cost_yen,lockedCapital:x.status==="OPEN"?x.reserved_yen:0,entryBuybackPrice:x.buyback_price_yen,entryProfit:x.market_profit_yen,openedAt:x.opened_at,closedAt:x.closed_at??undefined,status:x.status.toLowerCase()}));}
async function closeTrade(db:D1Database,id:number,at=new Date()){const row=await db.prepare(`SELECT t.*,o.canonical_product_id,o.sale_shipping_yen,o.fixed_fees_yen FROM research_paper_trades t JOIN research_opportunities o ON o.id=t.opportunity_id WHERE t.id=?`).bind(id).first<any>();if(!row)return null;if(row.status==="OPEN"){const best=await db.prepare(`SELECT p.price_yen-p.shipping_yen-p.fee_yen revenue FROM latest_prices p JOIN research_listings l ON l.id=p.listing_id WHERE l.canonical_product_id=? AND l.side='buyback' AND p.stock>0 ORDER BY revenue DESC LIMIT 1`).bind(row.canonical_product_id).first<any>();const revenue=(best?.revenue??row.reserved_yen)-row.sale_shipping_yen-row.fixed_fees_yen;await db.prepare("UPDATE research_paper_trades SET status='CLOSED',settlement_revenue_yen=?,closed_at=? WHERE id=? AND status='OPEN'").bind(revenue,at.toISOString(),id).run();}return (await listTrades(db)).find(x=>x.id===id)??null;}
async function evaluatorStatus(db:D1Database,at=new Date()){const schedules=(await db.prepare(`SELECT o.id decision_id,p.canonical_key,p.title,h.value horizon_hours,datetime(o.detected_at,'+'||h.value||' hours') due_at,e.evaluation_status,e.outcome,e.market_profit_yen,e.decay_yen,e.decay_rate FROM research_opportunities o JOIN canonical_products p ON p.id=o.canonical_product_id JOIN json_each('[24,48,72,168]') h LEFT JOIN research_opportunity_evaluations e ON e.opportunity_id=o.id AND e.horizon_hours=h.value ORDER BY due_at LIMIT 500`).all<any>()).results;const runs=(await db.prepare("SELECT * FROM evaluator_runs ORDER BY id DESC LIMIT 20").all<any>()).results;return{schedules:schedules.map(x=>({decisionId:x.decision_id,canonicalKey:x.canonical_key,title:x.title,horizonHours:x.horizon_hours,dueAt:x.due_at,status:x.evaluation_status==="completed"?"completed":x.evaluation_status==="pending_data"?"pending_data":(Date.parse(x.due_at)<=at.getTime()?"due":"pending"),outcome:x.outcome??undefined,profit:x.market_profit_yen??undefined,decay:x.decay_yen??undefined,decayRate:x.decay_rate??undefined})),runs:runs.map(x=>({id:x.id,trigger:x.trigger,status:x.status,evaluatedCount:x.evaluated_count,message:x.message,startedAt:x.started_at,finishedAt:x.finished_at}))};}
async function discoveryCandidates(db:D1Database,url:URL,amazonConfigured=false){
 const requested=Number.parseInt(url.searchParams.get("limit")??"1000",10),rowLimit=Math.max(1,Math.min(1000,Number.isFinite(requested)?requested:1000));
 const rows=(await db.prepare(`SELECT c.id,c.canonical_product_id,c.product_name,c.jan,c.model_number,c.brand,c.category,c.condition,c.attributes_json,c.best_buyback_price_yen,c.best_buyback_provider,c.buyback_provider_count,c.resolver_status,c.resolver_confidence,c.resolver_reason,c.search_query,c.target_purchase_price_yen,c.discovery_ceiling_yen,
  y.status yahoo_status,y.last_searched_at yahoo_last_searched_at,y.failure_count yahoo_failure_count,
  k.status rakuten_status,k.last_searched_at rakuten_last_searched_at,k.failure_count rakuten_failure_count,
  a.status amazon_status,a.last_searched_at amazon_last_searched_at,a.failure_count amazon_failure_count,
  COALESCE(r.result_count,0) retail_result_count,COALESCE(r.retail_provider_count,0) retail_provider_count,COALESCE(r.yahoo_result_count,0) yahoo_result_count,COALESCE(r.rakuten_result_count,0) rakuten_result_count,COALESCE(r.amazon_result_count,0) amazon_result_count,r.lowest_retail_price_yen,r.latest_result_at
  FROM product_discovery_candidates c
  LEFT JOIN product_discovery_provider_state y ON y.candidate_id=c.id AND y.provider='yahoo'
  LEFT JOIN product_discovery_provider_state k ON k.candidate_id=c.id AND k.provider='rakuten'
  LEFT JOIN product_discovery_provider_state a ON a.candidate_id=c.id AND a.provider='amazon'
  LEFT JOIN (SELECT candidate_id,COUNT(*) result_count,COUNT(DISTINCT source) retail_provider_count,SUM(CASE WHEN source='yahoo-discovery' THEN 1 ELSE 0 END) yahoo_result_count,SUM(CASE WHEN source='rakuten-discovery' THEN 1 ELSE 0 END) rakuten_result_count,SUM(CASE WHEN source='amazon-discovery' THEN 1 ELSE 0 END) amazon_result_count,MIN(price_yen) lowest_retail_price_yen,MAX(captured_at) latest_result_at FROM product_discovery_results GROUP BY candidate_id) r ON r.candidate_id=c.id
  ORDER BY c.buyback_provider_count DESC,c.best_buyback_price_yen DESC,c.id LIMIT ?`).bind(rowLimit).all<any>()).results;
 return{total:Number((await db.prepare("SELECT COUNT(*) count FROM product_discovery_candidates").first<any>())?.count??0),providers:amazonConfigured?["yahoo","rakuten","amazon"]:["yahoo","rakuten"],items:rows.map(x=>{const lowest=x.lowest_retail_price_yen==null?null:Number(x.lowest_retail_price_yen),profit=lowest==null?null:Number(x.best_buyback_price_yen)-lowest;return{id:x.id,canonicalProductId:x.canonical_product_id,productName:x.product_name,jan:x.jan,modelNumber:x.model_number,brand:x.brand,category:x.category,condition:x.condition,attributes:JSON.parse(x.attributes_json||"{}"),bestBuybackPrice:x.best_buyback_price_yen,bestBuybackProvider:x.best_buyback_provider,buybackProviderCount:x.buyback_provider_count,resolverStatus:x.resolver_status,resolverConfidence:x.resolver_confidence,resolverReason:x.resolver_reason,searchQuery:x.search_query,targetPurchasePrice:x.target_purchase_price_yen,discoveryCeiling:x.discovery_ceiling_yen,yahoo:{status:x.yahoo_status??"pending",lastSearchedAt:x.yahoo_last_searched_at??null,failureCount:Number(x.yahoo_failure_count??0),resultCount:Number(x.yahoo_result_count??0)},rakuten:{status:x.rakuten_status??"pending",lastSearchedAt:x.rakuten_last_searched_at??null,failureCount:Number(x.rakuten_failure_count??0),resultCount:Number(x.rakuten_result_count??0)},amazon:{status:x.amazon_status??"pending",lastSearchedAt:x.amazon_last_searched_at??null,failureCount:Number(x.amazon_failure_count??0),resultCount:Number(x.amazon_result_count??0)},retailResultCount:Number(x.retail_result_count??0),retailProviderCount:Number(x.retail_provider_count??0),lowestRetailPrice:lowest,estimatedProfit:profit,profitGap:profit==null?null:Math.max(5000-profit,0),latestResultAt:x.latest_result_at??null}})};
}

async function route(request:Request,env:Env):Promise<Response>{const url=new URL(request.url),path=url.pathname;
 if(request.method==="GET"&&path==="/health")return json({ok:true});
 if(request.method==="GET"&&path==="/api/ingest/targets") {if(!isAuthorized(request,env.INGEST_API_KEY))return json({error:"unauthorized"},401);const rows=(await env.DB.prepare(`SELECT p.canonical_key canonicalKey,p.gtin,p.manufacturer_part_number manufacturerPartNumber,p.brand,p.model,p.variant,p.category,p.capacity,p.color,p.condition,p.title,MIN(lp.price_yen+lp.shipping_yen-lp.reward_yen) purchasePrice FROM canonical_products p JOIN research_listings l ON l.canonical_product_id=p.id AND l.side='purchase' JOIN latest_prices lp ON lp.listing_id=l.id WHERE p.gtin IS NOT NULL AND p.gtin<>'' AND lp.stock>0 AND lp.captured_at>=datetime('now','-24 hours') GROUP BY p.id ORDER BY lp.captured_at DESC LIMIT ?`).bind(limit(url,100)).all()).results;return json({targets:rows});}
 if(request.method==="POST"&&path==="/api/ingest/buyback-quotes") {const token=env.SPREA_INGEST_TOKEN??env.INGEST_API_KEY;if(!isAuthorized(request,token))return json({error:"unauthorized"},401);const raw=await request.json<unknown>().catch(()=>null);if(!raw||typeof raw!=="object")return json({error:"invalid payload"},400);const input=raw as Record<string,unknown>;if(!Array.isArray(input.quotes)||input.quotes.length<1||input.quotes.length>500)return json({error:"quotes must contain between 1 and 500 items"},400);const useCase=new ImportBuybackQuotes(new D1BuybackQuoteRepository(env.DB),new D1ProductResolver(env.DB));const results=await useCase.execute({provider:input.provider,sourceType:input.sourceType,quotes:input.quotes});const accepted=results.filter(result=>result.accepted).length,productIds=results.flatMap(result=>result.accepted&&result.match?.matched?[result.match.matchedProductId]:[]);const opportunities=productIds.length?await createBuybackQuoteOpportunities(env.DB,productIds):{created:0,buys:0};return json({accepted,rejected:results.length-accepted,results,opportunities},accepted?202:400);}
 if(request.method==="POST"&&path==="/api/ingest/listings") {if(!isAuthorized(request,env.INGEST_API_KEY))return json({error:"unauthorized"},401);const raw=await request.json<unknown>().catch(()=>null) as IngestPayload|null;if(!raw||typeof raw.runId!=="string"||!raw.runId||typeof raw.source!=="string"||!raw.source||!Array.isArray(raw.listings)||raw.listings.length>500)return json({error:"invalid payload"},400);const listings=raw.listings.map(normalizeWireListing);if(!listings.every(validListing)||listings.some(x=>x.source!==raw.source))return json({error:"invalid payload"},400);const body={...raw,listings} as IngestPayload;const started=validTime(body.startedAt)?body.startedAt!:new Date().toISOString();await env.DB.prepare("INSERT INTO collector_runs(run_id,source,status,item_count,message,started_at,finished_at) VALUES(?,?, 'running',0,'',?,'') ON CONFLICT(run_id) DO NOTHING").bind(body.runId,body.source,started).run();try{const at=new Date(Math.max(...body.listings.map(x=>Date.parse(x.capturedAt)),Date.now()));const result=await ingestListings(env.DB,body.listings,at);const finished=validTime(body.finishedAt)?body.finishedAt!:new Date().toISOString();await env.DB.prepare("UPDATE collector_runs SET status='succeeded',item_count=?,message=?,finished_at=? WHERE run_id=?").bind(body.listings.length,`accepted ${body.listings.length} listings`,finished,body.runId).run();return json({runId:body.runId,...result},202);}catch(error){await env.DB.prepare("UPDATE collector_runs SET status='failed',message=?,finished_at=? WHERE run_id=?").bind(error instanceof Error?error.message.slice(0,1000):"ingest failed",new Date().toISOString(),body.runId).run();return json({error:error instanceof Error?error.message:"ingest failed"},422);}}
 if(request.method==="POST"&&path==="/admin/run"){if(!isAuthorized(request,env.ADMIN_TOKEN))return json({error:"unauthorized"},401);if(env.COLLECTOR_MODE!=="mock")return json({error:"mock collector is disabled"},409);const at=new Date(),runId=`admin-mock-${at.toISOString()}`;await env.DB.prepare("INSERT INTO collector_runs(run_id,source,status,item_count,message,started_at,finished_at) VALUES(?,?, 'running',0,'',?,'')").bind(runId,"mock",at.toISOString()).run();try{const result=await runPipeline(env.DB,new MockCollector(),at);await env.DB.prepare("UPDATE collector_runs SET status='succeeded',item_count=?,message=?,finished_at=? WHERE run_id=?").bind(result.observations,`accepted ${result.observations} listings; created ${result.opportunities} opportunities`,new Date().toISOString(),runId).run();return json(result);}catch(error){await env.DB.prepare("UPDATE collector_runs SET status='failed',message=?,finished_at=? WHERE run_id=?").bind(error instanceof Error?error.message.slice(0,1000):"collector failed",new Date().toISOString(),runId).run();throw error;}}
 if(request.method==="POST"&&path==="/admin/collect"){if(env.COLLECTOR_MODE==="mock")return json({error:"use /admin/run for local mock collection"},409);return json(await collectScheduled(env),202);}
 if(request.method==="POST"&&path==="/admin/discover"){const body=await request.json<{limit?:number}>().catch(()=>({} as {limit?:number}));return json(await runProductDiscovery(env,"manual",body.limit??10),202);}
 if(request.method==="GET"&&path==="/api/research/dashboard")return json(await dashboard(env.DB));
 if(request.method==="GET"&&path==="/api/research/discovery-candidates")return json(await discoveryCandidates(env.DB,url,Boolean(env.AMAZON_CREATORS_CLIENT_ID&&env.AMAZON_CREATORS_CLIENT_SECRET&&env.AMAZON_PARTNER_TAG)));
 if(request.method==="POST"&&path==="/api/research/discovery/run")return json(await runProductDiscovery(env,"manual",6),202);
 if(request.method==="GET"&&path==="/api/portfolio")return json(await env.DB.prepare("SELECT * FROM research_paper_accounts WHERE id=1").first());
 if(request.method==="GET"&&path==="/api/metrics"){const h=Number(url.searchParams.get("horizon")??48);if(![24,48,72,168].includes(h))return json({error:"invalid horizon"},400);const rows=(await env.DB.prepare("SELECT outcome,market_profit_yen FROM research_opportunity_evaluations WHERE horizon_hours=? AND evaluation_status='completed'").bind(h).all<any>()).results,tp=rows.filter(x=>x.outcome==="buy_correct").length,fp=rows.filter(x=>x.outcome==="buy_failed").length,fn=rows.filter(x=>x.outcome==="missed_opportunity").length,b=rows.filter(x=>String(x.outcome).startsWith("buy_"));return json({horizon_hours:h,precision:tp+fp?tp/(tp+fp):null,recall:tp+fn?tp/(tp+fn):null,average_profit_yen:b.length?b.reduce((s,x)=>s+x.market_profit_yen,0)/b.length:null,max_loss_yen:b.length?Math.min(...b.map(x=>x.market_profit_yen)):null,samples:rows.length});}
 const productMatch=path.match(/^\/api\/research\/products\/(.+)$/);if(request.method==="GET"&&productMatch){const result=await productDetail(env.DB,decodeURIComponent(productMatch[1]));return result?json(result):json({error:"not found"},404);}
 if(request.method==="GET"&&path==="/api/research/paper-trades")return json(await listTrades(env.DB));
 const closeMatch=path.match(/^\/api\/research\/paper-trades\/(\d+)\/close$/);if(request.method==="POST"&&closeMatch){const result=await closeTrade(env.DB,Number(closeMatch[1]));return result?json(result):json({error:"not found"},404);}
 if(request.method==="GET"&&path==="/api/research/settings"){const x=await env.DB.prepare("SELECT * FROM research_settings WHERE id=1").first<any>();return json({initialCapital:x.initial_capital_yen,minimumProfit:x.minimum_profit_yen,minimumConfidence:x.minimum_confidence,saleShipping:x.sale_shipping_yen,fees:x.fees_yen,evaluationHours:JSON.parse(x.evaluation_hours_json),maxPriceAgeMinutes:x.max_price_age_minutes});}
 if(request.method==="PUT"&&path==="/api/research/settings"){const x:Record<string,unknown>=await request.json<Record<string,unknown>>().catch(()=>({} as Record<string,unknown>)),hours=x.evaluationHours;if(!Number.isInteger(x.initialCapital)||Number(x.initialCapital)<=0||!Number.isInteger(x.minimumProfit)||Number(x.minimumProfit)<0||typeof x.minimumConfidence!=="number"||x.minimumConfidence<0||x.minimumConfidence>1||!Number.isInteger(x.saleShipping)||Number(x.saleShipping)<0||!Number.isInteger(x.fees)||Number(x.fees)<0||!Array.isArray(hours)||hours.join(",")!=="24,48,72,168"||(x.maxPriceAgeMinutes!==undefined&&(!Number.isInteger(x.maxPriceAgeMinutes)||Number(x.maxPriceAgeMinutes)<1||Number(x.maxPriceAgeMinutes)>1440)))return json({error:"invalid settings"},400);await env.DB.prepare("UPDATE research_settings SET initial_capital_yen=?,minimum_profit_yen=?,minimum_confidence=?,sale_shipping_yen=?,fees_yen=?,evaluation_hours_json=?,max_price_age_minutes=COALESCE(?,max_price_age_minutes),updated_at=? WHERE id=1").bind(x.initialCapital,x.minimumProfit,x.minimumConfidence,x.saleShipping,x.fees,JSON.stringify(hours),x.maxPriceAgeMinutes??null,new Date().toISOString()).run();return route(new Request(new URL("/api/research/settings",url),{method:"GET",headers:{authorization:request.headers.get("authorization")??""}}),env);}
 if(request.method==="GET"&&path==="/api/research/evaluator")return json(await evaluatorStatus(env.DB));
 if(request.method==="POST"&&path==="/api/research/evaluator/run"){const started=new Date(),insert=await env.DB.prepare("INSERT INTO evaluator_runs(trigger,status,started_at) VALUES('manual','running',?)").bind(started.toISOString()).run();const id=insert.meta.last_row_id;try{const count=await evaluateDue(env.DB,started);await env.DB.prepare("UPDATE evaluator_runs SET status='succeeded',evaluated_count=?,message=?,finished_at=? WHERE id=?").bind(count,`evaluated ${count} due checkpoints`,new Date().toISOString(),id).run();const runs=(await evaluatorStatus(env.DB)).runs;return json(runs.find(x=>x.id===id),202);}catch(e){await env.DB.prepare("UPDATE evaluator_runs SET status='failed',message=?,finished_at=? WHERE id=?").bind(e instanceof Error?e.message:"failed",new Date().toISOString(),id).run();throw e;}}
 if(request.method==="GET"&&path==="/api/collector/status"){
  const rows=(await env.DB.prepare("SELECT id,run_id runId,source,status,item_count itemCount,message,started_at startedAt,finished_at finishedAt FROM collector_runs ORDER BY id DESC LIMIT ?").bind(limit(url,20)).all()).results;
  const observed=(await env.DB.prepare(`SELECT provider source,'buyback' side,COUNT(*) itemCount,MAX(fetched_at) lastSuccessAt FROM buyback_quotes GROUP BY provider UNION ALL SELECT source,'retail' side,COUNT(*) itemCount,MAX(captured_at) lastSuccessAt FROM product_discovery_results GROUP BY source`).all<any>()).results;
  const sources=observed.map(source=>({...source,itemCount:Number(source.itemCount),status:"connected"}));
  const ensure=(source:string,side:string,configured:boolean)=>{if(configured&&!sources.some(item=>item.source===source))sources.push({source,side,itemCount:0,lastSuccessAt:null,status:"configured"})};
  ensure("yahoo-discovery","retail",Boolean(env.YAHOO_CLIENT_ID));ensure("rakuten-discovery","retail",Boolean(env.RAKUTEN_APPLICATION_ID&&env.RAKUTEN_ACCESS_KEY));ensure("amazon-discovery","retail",Boolean(env.AMAZON_CREATORS_CLIENT_ID&&env.AMAZON_CREATORS_CLIENT_SECRET&&env.AMAZON_PARTNER_TAG));
  return json({lastRun:rows[0]??null,runs:rows,sources});
 }
 return json({error:"not found"},404);
}

async function collectScheduled(env:Env,at=new Date()){
 if(env.COLLECTOR_MODE==="disabled")return{skipped:true,reason:"collector is disabled"};
 const source=env.COLLECTOR_MODE==="mock"?"mock":env.SPREA_COLLECTOR_SOURCE??"unconfigured";
 const runId=`worker-${source}-${at.toISOString()}`;
 await env.DB.prepare("INSERT INTO collector_runs(run_id,source,status,item_count,message,started_at,finished_at) VALUES(?,?, 'running',0,'',?,'') ON CONFLICT(run_id) DO NOTHING").bind(runId,source,at.toISOString()).run();
 try{
  const collector=env.COLLECTOR_MODE==="mock"?new MockCollector():collectorFromEnv(env);
  const result=await runPipeline(env.DB,collector,at);
  await env.DB.prepare("UPDATE collector_runs SET status='succeeded',item_count=?,message=?,finished_at=? WHERE run_id=?").bind(result.observations,`accepted ${result.observations} listings; created ${result.opportunities} opportunities`,new Date().toISOString(),runId).run();
  return{runId,source,...result};
 }catch(error){
  const message=error instanceof Error?error.message:"collector failed";
  await env.DB.prepare("UPDATE collector_runs SET status='failed',message=?,finished_at=? WHERE run_id=?").bind(message.slice(0,1000),new Date().toISOString(),runId).run();
  throw error;
 }
}

const isAllowedOrigin=(origin:string,configured?:string)=>{if(!origin)return false;if(origin===configured)return true;try{const url=new URL(origin);return url.protocol==="https:"&&(url.hostname==="sprea-frontend.pages.dev"||url.hostname.endsWith(".sprea-frontend.pages.dev"));}catch{return false;}};

export default{async fetch(request:Request,env:Env):Promise<Response>{const origin=request.headers.get("origin")??"",allowed=isAllowedOrigin(origin,env.ALLOWED_ORIGIN);const cors:Record<string,string>=allowed?{"access-control-allow-origin":origin,"access-control-allow-methods":"GET,POST,PUT,OPTIONS","access-control-allow-headers":"authorization,content-type","vary":"Origin"}:{};if(request.method==="OPTIONS")return new Response(null,{status:allowed?204:403,headers:cors});try{const response=await route(request,env);for(const[k,v]of Object.entries(cors))response.headers.set(k,v);return response;}catch(error){console.error(error);const response=json({error:"internal server error"},500);for(const[k,v]of Object.entries(cors))response.headers.set(k,v);return response;}},async scheduled(_c:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil((async()=>{await evaluateDue(env.DB);await collectScheduled(env);if(env.YAHOO_CLIENT_ID||(env.RAKUTEN_APPLICATION_ID&&env.RAKUTEN_ACCESS_KEY)||(env.AMAZON_CREATORS_CLIENT_ID&&env.AMAZON_CREATORS_CLIENT_SECRET&&env.AMAZON_PARTNER_TAG))await runProductDiscovery(env,"scheduled",20);})());}} satisfies ExportedHandler<Env>;
