import type {Collector,ListingObservation,RunSummary} from "./types";
import type {BuybackQuote} from "./domain";
import {stockStatusFromQuantity} from "./domain";
import {D1RetailListingRepository} from "./infrastructure/d1-retail-listing-repository";
import {aggregateBuybackQuotes} from "./application/buyback-quote-aggregator";
const HORIZONS=[24,48,72,168] as const,EVALUATION_LIMIT=100;
const norm=(v:string|undefined)=>v?.normalize("NFKC").trim().toUpperCase().replace(/[\s_-]+/g,"")||"";
const finiteInt=(v:number|undefined)=>Number.isInteger(v)&&Number(v)>=0?Number(v):0;
type Resolved={id:number;confidence:number;reason:string;key:string};
type Alias={type:"gtin"|"mpn"|"composite";value:string;confidence:number};
function aliases(o:ListingObservation):{condition:string;variant:string;items:Alias[]}{const condition=o.condition??"new",rawGtin=norm(o.gtin),gtin=/^\d{8,14}$/.test(rawGtin)?rawGtin:"",mpn=norm(o.manufacturerPartNumber),brand=norm(o.brand),model=norm(o.model),variant=norm(o.variant||o.capacity||o.color),items:Alias[]=[];if(gtin)items.push({type:"gtin",value:gtin,confidence:1});if(mpn)items.push({type:"mpn",value:`${mpn}:${variant}`,confidence:.99});if(brand&&model&&variant)items.push({type:"composite",value:`${brand}:${model}:${variant}`,confidence:.96});if(!items.length)throw new Error(`listing ${o.source}/${o.externalId} lacks a precision-safe product identity`);return{condition,variant,items};}
export async function resolveProduct(db:D1Database,o:ListingObservation):Promise<Resolved>{const a=aliases(o),matched=new Map<number,string>();for(const alias of a.items){const row=await db.prepare("SELECT canonical_product_id FROM canonical_product_aliases WHERE alias_type=? AND alias_value=? AND condition=?").bind(alias.type,alias.value,a.condition).first<{canonical_product_id:number}>();if(row)matched.set(row.canonical_product_id,alias.type);}if(matched.size>1)throw new Error(`conflicting canonical aliases for ${o.source}/${o.externalId}`);let id=[...matched.keys()][0],key="";const strongest=a.items[0];if(id){const current=await db.prepare("SELECT gtin,manufacturer_part_number FROM canonical_products WHERE id=?").bind(id).first<{gtin:string|null;manufacturer_part_number:string|null}>();const suppliedGtin=a.items.find(x=>x.type==="gtin")?.value,suppliedMpn=norm(o.manufacturerPartNumber);if(suppliedGtin&&current?.gtin&&suppliedGtin!==norm(current.gtin))throw new Error("conflicting GTIN for canonical product");if(suppliedMpn&&current?.manufacturer_part_number&&suppliedMpn!==norm(current.manufacturer_part_number))throw new Error("conflicting manufacturer part number for canonical product");}if(!id){key=`${strongest.type}:${strongest.value}:${a.condition}`;await db.prepare(`INSERT INTO canonical_products(canonical_key,gtin,manufacturer_part_number,brand,model,variant,category,capacity,color,condition,title,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(canonical_key) DO NOTHING`).bind(key,strongest.type==="gtin"?strongest.value:null,norm(o.manufacturerPartNumber)||null,o.brand??"",o.model,o.variant??o.capacity??o.color??"",o.category??"",o.capacity??"",o.color??"",a.condition,o.title,o.capturedAt,o.capturedAt).run();const row=await db.prepare("SELECT id FROM canonical_products WHERE canonical_key=?").bind(key).first<{id:number}>();if(!row)throw new Error("product resolution failed");id=row.id;}else{const p=await db.prepare("SELECT canonical_key FROM canonical_products WHERE id=?").bind(id).first<{canonical_key:string}>();key=p!.canonical_key;}
 for(const alias of a.items){const existing=await db.prepare("SELECT canonical_product_id FROM canonical_product_aliases WHERE alias_type=? AND alias_value=? AND condition=?").bind(alias.type,alias.value,a.condition).first<{canonical_product_id:number}>();if(existing&&existing.canonical_product_id!==id)throw new Error(`canonical alias collision for ${alias.type}`);await db.prepare("INSERT OR IGNORE INTO canonical_product_aliases(alias_type,alias_value,condition,canonical_product_id,created_at) VALUES(?,?,?,?,?)").bind(alias.type,alias.value,a.condition,id,o.capturedAt).run();}
 await db.prepare(`UPDATE canonical_products SET gtin=COALESCE(gtin,?),manufacturer_part_number=COALESCE(manufacturer_part_number,?),brand=CASE WHEN ?<>'' THEN ? ELSE brand END,model=CASE WHEN ?<>'' THEN ? ELSE model END,variant=CASE WHEN ?<>'' THEN ? ELSE variant END,category=CASE WHEN ?<>'' THEN ? ELSE category END,capacity=CASE WHEN ?<>'' THEN ? ELSE capacity END,color=CASE WHEN ?<>'' THEN ? ELSE color END,title=?,updated_at=MAX(updated_at,?) WHERE id=?`).bind((/^\d{8,14}$/.test(norm(o.gtin))?norm(o.gtin):null),norm(o.manufacturerPartNumber)||null,o.brand??"",o.brand??"",o.model,o.model,o.variant??"",o.variant??"",o.category??"",o.category??"",o.capacity??"",o.capacity??"",o.color??"",o.color??"",o.title,o.capturedAt,id).run();return{id,confidence:strongest.confidence,reason:`exact_${strongest.type}`,key};}

async function storeObservation(db:D1Database,product:Resolved,o:ListingObservation):Promise<number>{const shipping=finiteInt(o.shippingYen),fee=finiteInt(o.feeYen),reward=finiteInt(o.rewardYen),stockStatus=o.stockStatus??stockStatusFromQuantity(o.stock);await db.prepare(`INSERT INTO research_listings(canonical_product_id,source,external_id,side,title,url,resolver_confidence,match_reason,raw_json,first_seen_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(source,external_id) DO UPDATE SET canonical_product_id=excluded.canonical_product_id,side=excluded.side,title=excluded.title,url=excluded.url,resolver_confidence=excluded.resolver_confidence,match_reason=excluded.match_reason,raw_json=excluded.raw_json,updated_at=MAX(updated_at,excluded.updated_at)`).bind(product.id,o.source,o.externalId,o.side,o.title,o.url??"",product.confidence,product.reason,JSON.stringify(o.raw??{}),o.capturedAt,o.capturedAt).run();const listing=await db.prepare("SELECT id FROM research_listings WHERE source=? AND external_id=?").bind(o.source,o.externalId).first<{id:number}>();if(!listing)throw new Error("listing upsert failed");const previous=await db.prepare("SELECT price_yen,shipping_yen,fee_yen,reward_yen,stock,stock_status,captured_at FROM latest_prices WHERE listing_id=?").bind(listing.id).first<any>();const isLatest=!previous||o.capturedAt>=previous.captured_at,changed=isLatest&&(!previous||previous.price_yen!==o.priceYen||previous.shipping_yen!==shipping||previous.fee_yen!==fee||previous.reward_yen!==reward||previous.stock!==o.stock||previous.stock_status!==stockStatus);await db.prepare(`INSERT INTO latest_prices(listing_id,price_yen,shipping_yen,fee_yen,reward_yen,stock,captured_at,stock_status) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(listing_id) DO UPDATE SET price_yen=excluded.price_yen,shipping_yen=excluded.shipping_yen,fee_yen=excluded.fee_yen,reward_yen=excluded.reward_yen,stock=excluded.stock,captured_at=excluded.captured_at,stock_status=excluded.stock_status WHERE excluded.captured_at>latest_prices.captured_at`).bind(listing.id,o.priceYen,shipping,fee,reward,o.stock,o.capturedAt,stockStatus).run();if(!changed)return 0;const result=await db.prepare("INSERT OR IGNORE INTO research_price_snapshots(listing_id,price_yen,shipping_yen,fee_yen,reward_yen,stock,captured_at) VALUES(?,?,?,?,?,?,?)").bind(listing.id,o.priceYen,shipping,fee,reward,o.stock,o.capturedAt).run();return result.meta.changes??0;}
async function settings(db:D1Database){return(await db.prepare("SELECT * FROM research_settings WHERE id=1").first<any>())!;}
async function createOpportunities(db:D1Database,productIds:number[],at:Date):Promise<{created:number;buys:number}>{
 const config=await settings(db),retailRepository=new D1RetailListingRepository(db),buybackCutoff=new Date(at.getTime()-180*60_000).toISOString();let created=0,buys=0;
 for(const productId of [...new Set(productIds)]){
  const purchases=await retailRepository.findEligibleByProductId(String(productId),at),purchase=purchases.sort((a,b)=>(a.price+a.shippingFee-a.reward)-(b.price+b.shippingFee-b.reward))[0];
  const buybacks=(await db.prepare(`WITH candidates AS (SELECT l.id,l.resolver_confidence,CASE WHEN l.source LIKE 'buyback-quote:%' THEN substr(l.source,15) ELSE l.source END provider,p.price_yen,p.shipping_yen,p.fee_yen,p.stock,p.captured_at,ROW_NUMBER() OVER(PARTITION BY CASE WHEN l.source LIKE 'buyback-quote:%' THEN substr(l.source,15) ELSE l.source END ORDER BY p.captured_at DESC,l.id DESC) rank FROM research_listings l JOIN latest_prices p ON p.listing_id=l.id WHERE l.canonical_product_id=? AND l.side='buyback') SELECT * FROM candidates WHERE rank=1 AND stock>0 AND captured_at>? AND captured_at<=? ORDER BY (price_yen-shipping_yen-fee_yen) DESC,id LIMIT 20`).bind(productId,buybackCutoff,at.toISOString()).all<any>()).results;
  if(!purchase||!buybacks.length)continue;
  const purchaseRow=await db.prepare("SELECT resolver_confidence FROM research_listings WHERE id=?").bind(purchase.id).first<{resolver_confidence:number}>(),best=buybacks[0],second=buybacks[1],third=buybacks[2],cost=purchase.price+purchase.shippingFee-purchase.reward,revenue=best.price_yen-best.shipping_yen-best.fee_yen-config.sale_shipping_yen-config.fees_yen,profit=revenue-cost,rate=cost>0?profit/cost*100:0,confidence=Math.min(purchaseRow?.resolver_confidence??0,best.resolver_confidence),spreadRate=second&&best.price_yen?(best.price_yen-second.price_yen)/best.price_yen*100:null,bestSecondSpread=second?best.price_yen-second.price_yen:null,score=Math.max(0,Math.min(100,confidence*55+Math.max(0,Math.min(30,profit/500))+Math.min(15,buybacks.length*3))),decision=profit>=config.minimum_profit_yen&&confidence>=config.minimum_confidence?"BUY":"SKIP",reason=decision==="BUY"?"profit_and_identity_thresholds_met":profit<config.minimum_profit_yen?"profit_below_threshold":"resolver_confidence_below_threshold",features={effective_purchase_cost:cost,market_profit_yen:profit,profit_rate:rate,best_buyback_provider:best.provider,best_buyback_price:best.price_yen,second_buyback_provider:second?.provider??null,second_buyback_price:second?.price_yen??null,third_buyback_provider:third?.provider??null,third_buyback_price:third?.price_yen??null,buyback_source_count:buybacks.length,best_second_spread:bestSecondSpread,resolver_confidence:confidence,sprea_score:score},fingerprint=[productId,purchase.id,best.id,cost,revenue,config.minimum_profit_yen,config.minimum_confidence,buybacks.length,second?.id??"",third?.id??""].join(":");
  const result=await db.prepare(`INSERT OR IGNORE INTO research_opportunities(canonical_product_id,purchase_listing_id,buyback_listing_id,purchase_price_yen,purchase_shipping_yen,buyback_price_yen,buy_cost_yen,expected_revenue_yen,market_profit_yen,profit_rate,buyback_store_count,second_buyback_price_yen,top_two_spread_rate,resolver_confidence,sprea_score,decision,reason,features_json,detected_at,fingerprint,sale_shipping_yen,fixed_fees_yen,best_buyback_provider,second_buyback_provider,third_buyback_price_yen,third_buyback_provider,best_second_spread_yen) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(productId,purchase.id,best.id,purchase.price,purchase.shippingFee,best.price_yen,cost,revenue,profit,rate,buybacks.length,second?.price_yen??null,spreadRate,confidence,score,decision,reason,JSON.stringify(features),at.toISOString(),fingerprint,config.sale_shipping_yen,config.fees_yen,best.provider,second?.provider??null,third?.price_yen??null,third?.provider??null,bestSecondSpread).run();
  if(!result.meta.changes)continue;created++;
  if(decision==="BUY"){const opportunity=await db.prepare("SELECT id FROM research_opportunities WHERE fingerprint=?").bind(fingerprint).first<{id:number}>();if(opportunity)try{await db.prepare("INSERT INTO research_paper_trades(opportunity_id,reserved_yen,canonical_product_id,opened_at) VALUES(?,?,?,?)").bind(opportunity.id,cost,productId,at.toISOString()).run();buys++;}catch(error){const message=error instanceof Error?error.message:"";if(!/open position|insufficient paper cash/i.test(message))throw error;}}
 }
 return{created,buys};
}
export async function evaluateDue(db:D1Database,at=new Date()):Promise<number>{const due=(await db.prepare(`WITH horizons(hours) AS (VALUES(24),(48),(72),(168)) SELECT o.id opportunity_id,o.canonical_product_id,o.decision,o.buy_cost_yen,o.detected_at,o.sale_shipping_yen,o.fixed_fees_yen,t.id trade_id,h.hours horizon_hours FROM research_opportunities o CROSS JOIN horizons h LEFT JOIN research_paper_trades t ON t.opportunity_id=o.id LEFT JOIN research_evaluations e ON e.opportunity_id=o.id AND e.horizon_hours=h.hours WHERE e.id IS NULL AND datetime(o.detected_at,'+'||h.hours||' hours')<=datetime(?) ORDER BY o.detected_at,h.hours LIMIT ?`).bind(at.toISOString(),EVALUATION_LIMIT).all<any>()).results;let count=0;for(const row of due){const targetHours=Number(row.horizon_hours),target=new Date(Date.parse(row.detected_at)+targetHours*3600000).toISOString();const sell=await db.prepare(`WITH observations AS (SELECT s.id snapshot_id,s.listing_id,s.price_yen,s.shipping_yen,s.fee_yen,s.stock,s.captured_at FROM research_price_snapshots s UNION SELECT (SELECT s.id FROM research_price_snapshots s WHERE s.listing_id=p.listing_id AND s.captured_at<=p.captured_at ORDER BY s.captured_at DESC,s.id DESC LIMIT 1) snapshot_id,p.listing_id,p.price_yen,p.shipping_yen,p.fee_yen,p.stock,p.captured_at FROM latest_prices p), first_per_listing AS (SELECT ob.*,ROW_NUMBER() OVER(PARTITION BY ob.listing_id ORDER BY ob.captured_at,ob.snapshot_id) rn FROM observations ob JOIN research_listings l ON l.id=ob.listing_id WHERE l.canonical_product_id=? AND l.side='buyback' AND ob.stock>0 AND ob.captured_at>=? AND ob.captured_at<=?) SELECT snapshot_id,price_yen,price_yen-shipping_yen-fee_yen revenue FROM first_per_listing WHERE rn=1 AND snapshot_id IS NOT NULL ORDER BY revenue DESC,snapshot_id LIMIT 1`).bind(row.canonical_product_id,target,at.toISOString()).first<any>();if(!sell)continue;const profit=sell.revenue-row.sale_shipping_yen-row.fixed_fees_yen-row.buy_cost_yen,good=profit>=5000,outcome=row.decision==="BUY"?(good?"buy_correct":"buy_failed"):(good?"missed_opportunity":"skip_correct"),result=await db.prepare("INSERT OR IGNORE INTO research_evaluations(opportunity_id,trade_id,horizon_hours,buyback_snapshot_id,buyback_price_yen,profit_yen,target_met,outcome,evaluated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(row.opportunity_id,row.trade_id??null,targetHours,sell.snapshot_id,sell.price_yen,profit,good?1:0,outcome,at.toISOString()).run();count+=result.meta.changes??0;if(targetHours===168&&row.trade_id&&result.meta.changes)await db.prepare("UPDATE research_paper_trades SET status='CLOSED',settlement_revenue_yen=?,closed_at=? WHERE id=? AND status='OPEN'").bind(sell.revenue-row.sale_shipping_yen-row.fixed_fees_yen,at.toISOString(),row.trade_id).run();}return count;}

/** Projects eligible imported quotes into the existing listing engine without changing legacy collectors. */
export async function createBuybackQuoteOpportunities(db:D1Database,productIds:string[],at=new Date()):Promise<{created:number;buys:number}>{
 const ids=[...new Set(productIds.map(Number).filter(Number.isSafeInteger))];
 for(const productId of ids){const rows=(await db.prepare("SELECT * FROM buyback_quotes WHERE product_id=? ORDER BY fetched_at DESC").bind(productId).all<any>()).results;
  const quotes:BuybackQuote[]=rows.map(row=>({id:String(row.id),productId:String(row.product_id),provider:String(row.provider),sourceType:row.source_type,externalId:row.external_id??undefined,productName:String(row.product_name),jan:row.jan??undefined,modelNumber:row.model_number??undefined,brand:row.brand??undefined,category:row.category??undefined,condition:row.condition,attributes:JSON.parse(String(row.attributes_json||"{}")),price:Number(row.price),shippingFee:Number(row.shipping_fee),fee:Number(row.fee),buybackStatus:row.buyback_status,productUrl:row.product_url??undefined,fetchedAt:String(row.fetched_at),lastSeenAt:String(row.last_seen_at),matchConfidence:Number(row.match_confidence),matchReason:String(row.match_reason)}));
  const aggregate=aggregateBuybackQuotes(quotes,at);
  await db.prepare("UPDATE latest_prices SET stock=0 WHERE listing_id IN (SELECT id FROM research_listings WHERE canonical_product_id=? AND source LIKE 'buyback-quote:%')").bind(productId).run();
  for(const ranked of aggregate?.ranked??[]){const quote=ranked.quote,source=`buyback-quote:${quote.provider}`,externalId=quote.externalId||quote.id;
   await db.prepare(`INSERT INTO research_listings(canonical_product_id,source,external_id,side,title,url,resolver_confidence,match_reason,raw_json,first_seen_at,updated_at) VALUES(?,?,?,'buyback',?,?,?,?,?,?,?) ON CONFLICT(source,external_id) DO UPDATE SET canonical_product_id=excluded.canonical_product_id,title=excluded.title,url=excluded.url,resolver_confidence=excluded.resolver_confidence,match_reason=excluded.match_reason,raw_json=excluded.raw_json,updated_at=excluded.updated_at`).bind(productId,source,externalId,quote.productName,quote.productUrl??"",quote.matchConfidence??0,quote.matchReason??"unresolved",JSON.stringify({buybackQuoteId:quote.id,attributes:quote.attributes}),quote.fetchedAt,quote.fetchedAt).run();
   const listing=await db.prepare("SELECT id FROM research_listings WHERE source=? AND external_id=?").bind(source,externalId).first<{id:number}>();if(!listing)throw new Error("buyback quote projection failed");
   await db.prepare(`INSERT INTO latest_prices(listing_id,price_yen,shipping_yen,fee_yen,reward_yen,stock,captured_at,stock_status) VALUES(?,?,?,?,0,1,?,'in_stock') ON CONFLICT(listing_id) DO UPDATE SET price_yen=excluded.price_yen,shipping_yen=excluded.shipping_yen,fee_yen=excluded.fee_yen,stock=1,captured_at=excluded.captured_at,stock_status='in_stock'`).bind(listing.id,quote.price,quote.shippingFee,quote.fee,quote.fetchedAt).run();
   await db.prepare("INSERT OR IGNORE INTO research_price_snapshots(listing_id,price_yen,shipping_yen,fee_yen,reward_yen,stock,captured_at) VALUES(?,?,?,?,0,1,?)").bind(listing.id,quote.price,quote.shippingFee,quote.fee,quote.fetchedAt).run();
  }
 }
 return createOpportunities(db,ids,at);
}
export async function ingestListings(db:D1Database,observations:ListingObservation[],at=new Date()):Promise<RunSummary>{const products:number[]=[];let snapshots=0;for(const o of observations){const p=await resolveProduct(db,o);products.push(p.id);snapshots+=await storeObservation(db,p,o);}const opportunities=await createOpportunities(db,products,at),evaluations=await evaluateDue(db,at);return{observations:observations.length,products:new Set(products).size,snapshots,opportunities:opportunities.created,buys:opportunities.buys,evaluations};}
export async function runPipeline(db:D1Database,collector:Collector,at=new Date()):Promise<RunSummary>{return ingestListings(db,await collector.collect(at),at);}
